// ========================================================
// MOCK DATA - DỮ LIỆU MINH HỌA DOANH NGHIỆP TOÀN DIỆN
// Bao gồm: An Việt Manufacturing (Sản xuất thực phẩm) & DigiTech (Công nghệ)
// 15 Kịch bản nhân sự mẫu chuẩn hóa cho Kiểm Tra Ngược Chuyển Khoản Ngân Hàng
// ========================================================

import { CompanyPolicy, Employee, ShiftDefinition, AccountingJournalEntry, AttendanceRecord, WorkflowRequest, OffboardingRecord, FeedbackItem, PersonnelChange, JobDescription, TrainingCourse } from '../types/hrm';
import { PayrollCalculationOptions } from './payrollEngine';

export const initialPolicies: CompanyPolicy[] = [
  {
    id: 'POL-01',
    tenantId: 'TENANT-ASIAFOODS',
    companyName: 'An Việt Manufacturing',
    taxCode: '3700147982',
    industry: 'MANUFACTURING',
    payrollCycleType: 'CYCLE_26_TO_25', // Chu kỳ từ 26 tháng trước đến 25 tháng này
    standardWorkDaysPerMonth: 26,
    saturdayPolicy: 'MORNING_ONLY', // Sáng thứ 7 làm việc, chiều nghỉ
    allowRemoteOnline: false,
    lateRuleLevel1Minutes: 5,  // 0-5m trừ 30m
    lateRuleLevel2Minutes: 15, // 5-15m trừ 60m
    lateRuleLevel3Minutes: 16, // >15m không tính công khung giờ đó
    otDayNormalRate: 1.5,
    otDayWeekendRate: 2.0,
    otDayHolidayRate: 3.0,
    nightWorkBonusRate: 0.3,
    otNightNormalRate: 2.1,
    otNightWeekendRate: 2.7,
    otNightHolidayRate: 3.9,
    toxicAllowanceTier1: 13000,
    toxicAllowanceTier2: 20000, // Thường áp dụng cho công nhân xưởng đóng gói
    toxicAllowanceTier3: 26000, // Công nhân trực tiếp lò sấy / khu vực nhiệt độ cao
    toxicAllowanceTier4: 32000,
    maxCarryOverDays: 4,
    carryOverExpiryDate: '31/03',
    regionalMinimumWage: 5310000, // Vùng 1 mới nhất theo Nghị định 293/2025/NĐ-CP
    personalDeduction: 11000000, // Biểu cũ 7 bậc (trước ngày áp dụng)
    dependentDeduction: 4400000, // Biểu cũ 7 bậc (trước ngày áp dụng)
    pitTableType: 'AUTO_BY_DATE', // Tự động nhận diện theo mốc ngày áp dụng
    pit5TiersEffectiveDate: '2026-01-01', // Ngày áp dụng Biểu thuế 5 bậc (Luật Thuế TNCN 109/2025/QH15)
    pit5PersonalDeduction: 14000000, // Mức giảm trừ bản thân dự kiến theo luật mới
    pit5DependentDeduction: 5500000, // Mức giảm trừ người phụ thuộc dự kiến theo luật mới
    bhxhEmpRate: 0.08,
    bhytEmpRate: 0.015,
    bhtnEmpRate: 0.01,
    bhxhCompRate: 0.175,
    bhytCompRate: 0.03,
    bhtnCompRate: 0.01,
    unionCompanyRate: 0.02,
    unionMemberRate: 0.01,
    shiftMealAllowancePerDay: 40000, // Tiền ăn ca thực tế 40.000 đ/ngày (1.040.000 đ/tháng 26 công, cập nhật thay thế mức cũ 730k)
    shiftMealEffectiveDate: '2026-01-01',
    shiftMealPaymentType: 'PER_DAY',
    companyBusinessPerformanceRate: 105, // 105% kế hoạch kinh doanh
    productSalaryPerformanceRate: 102, // 102% nhóm lương sản phẩm
    volumeSalaryPerformanceRate: 108, // 108% nhóm lương sản lượng
    kpiSalaryPerformanceRate: 100, // 100% nhóm lương KPI
    salaryGroupRatesEffectiveDate: '2026-08-01',
    thousandSeparator: '.',
    decimalSeparator: ',',
    defaultLanguage: 'vi',
  },
  {
    id: 'POL-02',
    tenantId: 'TENANT-DIGITECH',
    companyName: 'DigiTech',
    taxCode: '0108992341',
    industry: 'TECHNOLOGY',
    payrollCycleType: 'MONTH_START_END', // Chu kỳ 01 đến cuối tháng
    standardWorkDaysPerMonth: 22,
    saturdayPolicy: 'FULL_OFF', // Nghỉ toàn bộ thứ 7
    allowRemoteOnline: true, // Thứ 7 hoặc làm việc từ xa tự động tính công
    lateRuleLevel1Minutes: 15,
    lateRuleLevel2Minutes: 30,
    lateRuleLevel3Minutes: 60,
    otDayNormalRate: 1.5,
    otDayWeekendRate: 2.0,
    otDayHolidayRate: 3.0,
    nightWorkBonusRate: 0.3,
    otNightNormalRate: 2.1,
    otNightWeekendRate: 2.7,
    otNightHolidayRate: 3.9,
    toxicAllowanceTier1: 0,
    toxicAllowanceTier2: 0,
    toxicAllowanceTier3: 0,
    toxicAllowanceTier4: 0,
    maxCarryOverDays: 5,
    carryOverExpiryDate: '31/03',
    regionalMinimumWage: 5310000,
    personalDeduction: 11000000,
    dependentDeduction: 4400000,
    pitTableType: 'AUTO_BY_DATE',
    pit5TiersEffectiveDate: '2026-01-01',
    pit5PersonalDeduction: 14000000,
    pit5DependentDeduction: 5500000,
    bhxhEmpRate: 0.08,
    bhytEmpRate: 0.015,
    bhtnEmpRate: 0.01,
    bhxhCompRate: 0.175,
    bhytCompRate: 0.03,
    bhtnCompRate: 0.01,
    unionCompanyRate: 0.02,
    unionMemberRate: 0.01,
    shiftMealAllowancePerDay: 50000, // 50.000 đ/ngày làm việc
    shiftMealEffectiveDate: '2026-01-01',
    shiftMealPaymentType: 'MONTHLY_FIXED',
    companyBusinessPerformanceRate: 110,
    productSalaryPerformanceRate: 100,
    volumeSalaryPerformanceRate: 100,
    kpiSalaryPerformanceRate: 112,
    salaryGroupRatesEffectiveDate: '2026-08-01',
    thousandSeparator: '.',
    decimalSeparator: ',',
    defaultLanguage: 'vi',
  }
];

export const initialShifts: ShiftDefinition[] = [
  {
    id: 'SHIFT-01',
    code: 'CA-HC',
    name: 'Ca Hành Chính Văn Phòng',
    startTime: '08:00',
    endTime: '17:00',
    breakDurationMinutes: 60,
    workHours: 8.0,
    isNightShift: false,
    shiftType: 'ADMINISTRATIVE',
  },
  {
    id: 'SHIFT-02',
    code: 'CA-1',
    name: 'Ca Sáng Nhà Máy (Ca 1)',
    startTime: '06:00',
    endTime: '14:00',
    breakDurationMinutes: 45,
    workHours: 7.25,
    isNightShift: false,
    shiftType: 'MORNING',
  },
  {
    id: 'SHIFT-03',
    code: 'CA-2',
    name: 'Ca Chiều Nhà Máy (Ca 2)',
    startTime: '14:00',
    endTime: '22:00',
    breakDurationMinutes: 45,
    workHours: 7.25,
    isNightShift: false,
    shiftType: 'AFTERNOON',
  },
  {
    id: 'SHIFT-04',
    code: 'CA-3',
    name: 'Ca Đêm Nhà Máy (Ca 3)',
    startTime: '22:00',
    endTime: '06:00',
    breakDurationMinutes: 60,
    workHours: 7.0,
    isNightShift: true,
    shiftType: 'NIGHT',
  },
  {
    id: 'SHIFT-05',
    code: 'CA-12H',
    name: 'Ca Sản Xuất 12 Tiếng (Gồm 4h OT)',
    startTime: '07:00',
    endTime: '19:00',
    breakDurationMinutes: 60,
    workHours: 11.0,
    isNightShift: false,
    shiftType: 'FACTORY_12H',
  }
];

// ========================================================
// 15 NHÂN VIÊN MẪU TOÀN DIỆN CHO MỌI TRƯỜNG HỢP KIỂM TRA NGƯỢC
// ========================================================
export const initialEmployees: Employee[] = [
  // 0. CHỦ TỊCH HỘI ĐỒNG QUẢN TRỊ
  {
    id: 'EMP-000',
    tenantId: 'TENANT-ASIAFOODS',
    code: 'AF-000',
    fullName: 'Lê Hoàng Hải',
    gender: 'MALE',
    dob: '1970-02-15',
    phone: '0903889988',
    email: 'hai.le@anviet.vn',
    cccd: '079070000001',
    cccdDate: '2021-01-10',
    cccdPlace: 'Cục Cảnh sát QLHC về TTXH',
    address: 'Quận 1, TP. Hồ Chí Minh',
    branchId: 'BR-01',
    branchName: 'Trụ Sở Chính TP.HCM',
    departmentId: 'DEPT-01',
    departmentName: 'Hội Đồng Quản Trị',
    position: 'Chủ Tịch Hội Đồng Quản Trị',
    role: 'GENERAL_DIRECTOR',
    status: 'OFFICIAL',
    contractType: 'INDEFINITE',
    contractNumber: 'HDLD-HĐQT-001',
    joinDate: '2014-01-01',
    contractStartDate: '2014-01-01',
    bankAccountNumber: '0071000999999',
    bankName: 'Vietcombank',
    taxCode: '8012345000',
    socialInsuranceNumber: '7914000001',
    numberOfDependents: 2,
    baseSalary: 75000000,
    positionSalary: 30000000,
    lunchAllowance: 730000,
    transportAllowance: 8000000,
    phoneAllowance: 3000000,
    toxicTier: 0,
    annualLeaveTotal: 16,
    annualLeaveUsed: 2,
    annualLeaveCarriedOver: 4,
  },

  // 1. TỔNG GIÁM ĐỐC (Lương cao, chạm trần BHXH, thuế bậc 7, 2 NPT)
  {
    id: 'EMP-001',
    tenantId: 'TENANT-ASIAFOODS',
    code: 'AF-001',
    fullName: 'ThS. Nguyễn Văn Hùng',
    gender: 'MALE',
    dob: '1975-04-12',
    phone: '0903123456',
    email: 'hung.nguyen@anviet.vn',
    cccd: '079075001234',
    cccdDate: '2021-05-10',
    cccdPlace: 'Cục Cảnh sát QLHC về TTXH',
    address: 'Quận 1, TP. Hồ Chí Minh',
    branchId: 'BR-01',
    branchName: 'Trụ Sở Chính TP.HCM',
    departmentId: 'DEPT-01',
    departmentName: 'Ban Tổng Giám Đốc',
    position: 'Tổng Giám Đốc (CEO)',
    role: 'GENERAL_DIRECTOR',
    managerId: 'EMP-000',
    status: 'OFFICIAL',
    contractType: 'INDEFINITE',
    contractNumber: 'HDLD-2020-001',
    joinDate: '2015-01-01',
    contractStartDate: '2015-01-01',
    bankAccountNumber: '0071000123456',
    bankName: 'Vietcombank',
    taxCode: '8012345678',
    socialInsuranceNumber: '7915001234',
    numberOfDependents: 2,
    baseSalary: 65000000, // Vượt trần BHXH 46.8tr
    positionSalary: 20000000,
    lunchAllowance: 730000,
    transportAllowance: 5000000,
    phoneAllowance: 2000000,
    toxicTier: 0,
    annualLeaveTotal: 15,
    annualLeaveUsed: 3,
    annualLeaveCarriedOver: 2,
  },

  // 2. TRƯỞNG PHÒNG NHÂN SỰ (Chính thức chuẩn, đủ công, thuế bậc 3-4, 1 NPT)
  {
    id: 'EMP-002',
    tenantId: 'TENANT-ASIAFOODS',
    code: 'AF-002',
    fullName: 'Trần Thị Thu Trang',
    gender: 'FEMALE',
    dob: '1985-08-20',
    phone: '0918998877',
    email: 'trang.tran@anviet.vn',
    cccd: '079185005678',
    cccdDate: '2022-03-15',
    cccdPlace: 'Cục Cảnh sát QLHC về TTXH',
    address: 'Thành phố Thủ Đức, TP.HCM',
    branchId: 'BR-01',
    branchName: 'Trụ Sở Chính TP.HCM',
    departmentId: 'DEPT-02',
    departmentName: 'Phòng Nhân Sự',
    position: 'Trưởng Phòng Nhân Sự',
    role: 'HR_MANAGER',
    managerId: 'EMP-001',
    status: 'OFFICIAL',
    contractType: 'INDEFINITE',
    contractNumber: 'HDLD-2018-024',
    joinDate: '2018-06-01',
    contractStartDate: '2018-06-01',
    bankAccountNumber: '19032456789012',
    bankName: 'Techcombank',
    taxCode: '8099887766',
    socialInsuranceNumber: '7918005678',
    numberOfDependents: 1,
    baseSalary: 25000000,
    positionSalary: 10000000,
    lunchAllowance: 730000,
    transportAllowance: 2000000,
    phoneAllowance: 1000000,
    toxicTier: 0,
    annualLeaveTotal: 14,
    annualLeaveUsed: 4,
    annualLeaveCarriedOver: 3,
  },

  // 3. CHUYÊN VIÊN C&B (Nghỉ 1 ngày phép năm hưởng nguyên 100% lương)
  {
    id: 'EMP-003',
    tenantId: 'TENANT-ASIAFOODS',
    code: 'AF-003',
    fullName: 'Lê Hoàng Nam',
    gender: 'MALE',
    dob: '1992-11-05',
    phone: '0987654321',
    email: 'nam.le@anviet.vn',
    cccd: '079092008899',
    cccdDate: '2021-08-10',
    cccdPlace: 'Cục Cảnh sát QLHC về TTXH',
    address: 'Quận Bình Thạnh, TP.HCM',
    branchId: 'BR-01',
    branchName: 'Trụ Sở Chính TP.HCM',
    departmentId: 'DEPT-02',
    departmentName: 'Phòng Nhân Sự',
    position: 'Chuyên Viên C&B (Tiền Lương & Phúc Lợi)',
    role: 'PAYROLL_SPECIALIST',
    managerId: 'EMP-002',
    status: 'OFFICIAL',
    contractType: 'DEFINITE_24M',
    contractNumber: 'HDLD-2022-105',
    joinDate: '2022-02-15',
    contractStartDate: '2022-02-15',
    bankAccountNumber: '0071000987654',
    bankName: 'Vietcombank',
    taxCode: '8033221100',
    socialInsuranceNumber: '7922008899',
    numberOfDependents: 0,
    baseSalary: 16000000,
    positionSalary: 2000000,
    lunchAllowance: 730000,
    transportAllowance: 1000000,
    phoneAllowance: 500000,
    toxicTier: 0,
    annualLeaveTotal: 12,
    annualLeaveUsed: 2,
    annualLeaveCarriedOver: 1,
  },

  // 4. NHÂN VIÊN THỬ VIỆC MARKETING (Lương 85%, không BHXH, khấu trừ 10% thuế TNCN)
  {
    id: 'EMP-004',
    tenantId: 'TENANT-ASIAFOODS',
    code: 'AF-004',
    fullName: 'Phạm Thị Lan',
    gender: 'FEMALE',
    dob: '1999-07-22',
    phone: '0933112233',
    email: 'lan.pham@anviet.vn',
    cccd: '079199003344',
    cccdDate: '2023-01-20',
    cccdPlace: 'Cục Cảnh sát QLHC về TTXH',
    address: 'Quận Gò Vấp, TP.HCM',
    branchId: 'BR-01',
    branchName: 'Trụ Sở Chính TP.HCM',
    departmentId: 'DEPT-04',
    departmentName: 'Phòng Tiếp Thị & Marketing',
    position: 'Nhân Viên Digital Marketing (Thử việc)',
    role: 'EMPLOYEE',
    managerId: 'EMP-002',
    status: 'PROBATION',
    contractType: 'PROBATION',
    contractNumber: 'HDTV-2026-092',
    joinDate: '2026-07-01',
    contractStartDate: '2026-07-01',
    contractEndDate: '2026-08-31',
    bankAccountNumber: '0380123456789',
    bankName: 'MB Bank',
    taxCode: '8066778899',
    socialInsuranceNumber: '',
    numberOfDependents: 0,
    baseSalary: 12000000,
    probationRate: 0.85, // 85% = 10.200.000đ
    positionSalary: 1000000,
    lunchAllowance: 730000,
    transportAllowance: 500000,
    phoneAllowance: 0,
    toxicTier: 0,
    annualLeaveTotal: 2,
    annualLeaveUsed: 0,
    annualLeaveCarriedOver: 0,
  },

  // 5. CÔNG NHÂN CA ĐÊM & ĐỘC HẠI (Ca 22h-6h hưởng +30%, sữa hộp TT24 không cộng tiền chuyển khoản)
  {
    id: 'EMP-005',
    tenantId: 'TENANT-ASIAFOODS',
    code: 'AF-005',
    fullName: 'Hoàng Văn Đức',
    gender: 'MALE',
    dob: '1988-03-10',
    phone: '0978665544',
    email: 'duc.hoang@anviet.vn',
    cccd: '079088002233',
    cccdDate: '2020-11-12',
    cccdPlace: 'Cục Cảnh sát QLHC về TTXH',
    address: 'Huyện Củ Chi, TP.HCM',
    branchId: 'BR-02',
    branchName: 'Nhà Máy Chế Biến Thực Phẩm Bình Dương',
    departmentId: 'DEPT-03',
    departmentName: 'Phân Xưởng Đóng Gói',
    position: 'Kỹ Thuật Viên Vận Hành Máy Đóng Gói (Ca đêm)',
    role: 'EMPLOYEE',
    status: 'OFFICIAL',
    contractType: 'INDEFINITE',
    contractNumber: 'HDLD-2019-331',
    joinDate: '2019-08-01',
    contractStartDate: '2019-08-01',
    bankAccountNumber: '6280205123456',
    bankName: 'Agribank',
    taxCode: '8022334455',
    socialInsuranceNumber: '7919002233',
    numberOfDependents: 1,
    baseSalary: 8500000,
    positionSalary: 1000000,
    lunchAllowance: 730000,
    transportAllowance: 600000,
    phoneAllowance: 0,
    toxicTier: 2, // 20.000đ/ngày x 24 ngày = 480.000đ hiện vật (NON-CASH)
    annualLeaveTotal: 13,
    annualLeaveUsed: 3,
    annualLeaveCarriedOver: 2,
  },

  // 6. TRƯỞNG NHÓM KINH DOANH (Thưởng KPI cao 15tr, trừ tạm ứng lương 5tr vào chuyển khoản)
  {
    id: 'EMP-006',
    tenantId: 'TENANT-ASIAFOODS',
    code: 'AF-006',
    fullName: 'Vũ Đình Trọng',
    gender: 'MALE',
    dob: '1990-12-25',
    phone: '0919887766',
    email: 'trong.vu@anviet.vn',
    cccd: '079090001122',
    cccdDate: '2021-04-18',
    cccdPlace: 'Cục Cảnh sát QLHC về TTXH',
    address: 'Quận Tân Bình, TP.HCM',
    branchId: 'BR-01',
    branchName: 'Trụ Sở Chính TP.HCM',
    departmentId: 'DEPT-05',
    departmentName: 'Khối Kinh Doanh Toàn Quốc',
    position: 'Trưởng Nhóm Kinh Doanh Bán Lẻ (Sales Lead)',
    role: 'EMPLOYEE',
    managerId: 'EMP-001',
    status: 'OFFICIAL',
    contractType: 'INDEFINITE',
    contractNumber: 'HDLD-2021-055',
    joinDate: '2021-03-01',
    contractStartDate: '2021-03-01',
    bankAccountNumber: '12410001234567',
    bankName: 'BIDV',
    taxCode: '8011223344',
    socialInsuranceNumber: '7921001122',
    numberOfDependents: 1,
    baseSalary: 10000000,
    positionSalary: 3000000,
    lunchAllowance: 730000,
    transportAllowance: 2500000,
    phoneAllowance: 1500000,
    toxicTier: 0,
    annualLeaveTotal: 13,
    annualLeaveUsed: 2,
    annualLeaveCarriedOver: 1,
  },

  // 7. CHUYÊN GIA NƯỚC NGOÀI / KHÔNG CƯ TRÚ (Khấu trừ thuế phẳng 20% toàn bộ, không trừ gia cảnh)
  {
    id: 'EMP-007',
    tenantId: 'TENANT-ASIAFOODS',
    code: 'AF-007',
    fullName: 'Michael Johnson',
    gender: 'MALE',
    dob: '1982-06-18',
    phone: '0909998877',
    email: 'michael.johnson@anviet.vn',
    cccd: 'P98765432',
    cccdDate: '2023-01-10',
    cccdPlace: 'Cục Quản lý Xuất Nhập Cảnh',
    address: 'Thảo Điền, TP. Thủ Đức, TP.HCM',
    branchId: 'BR-01',
    branchName: 'Trụ Sở Chính TP.HCM',
    departmentId: 'DEPT-01',
    departmentName: 'Ban Tổng Giám Đốc',
    position: 'Cố Vấn Chiến Lược Công Nghệ Cao (Chuyên gia nước ngoài)',
    role: 'EMPLOYEE',
    managerId: 'EMP-001',
    status: 'OFFICIAL',
    contractType: 'DEFINITE_12M',
    contractNumber: 'HDLD-EXP-2026-01',
    joinDate: '2026-01-15',
    contractStartDate: '2026-01-15',
    contractEndDate: '2027-01-15',
    bankAccountNumber: '0071000777888',
    bankName: 'Vietcombank',
    taxCode: '8099112233',
    socialInsuranceNumber: '7926009911',
    numberOfDependents: 0,
    baseSalary: 60000000,
    positionSalary: 10000000,
    lunchAllowance: 730000,
    transportAllowance: 3000000,
    phoneAllowance: 1000000,
    toxicTier: 0,
    isNonResident: true, // Cá nhân không cư trú -> Thuế 20% flat
    annualLeaveTotal: 12,
    annualLeaveUsed: 1,
    annualLeaveCarriedOver: 0,
  },

  // 8. NHÂN VIÊN THÔI VIỆC GIỮA THÁNG (Thanh lý 10 công, tiền phép tồn 2 ngày, trừ công nợ bồi hoàn 500k)
  {
    id: 'EMP-008',
    tenantId: 'TENANT-ASIAFOODS',
    code: 'AF-008',
    fullName: 'Đỗ Thị Thu Hiền',
    gender: 'FEMALE',
    dob: '1994-09-15',
    phone: '0988223344',
    email: 'hien.do@anviet.vn',
    cccd: '079194008877',
    cccdDate: '2022-07-20',
    cccdPlace: 'Cục Cảnh sát QLHC về TTXH',
    address: 'Quận Phú Nhuận, TP.HCM',
    branchId: 'BR-01',
    branchName: 'Trụ Sở Chính TP.HCM',
    departmentId: 'DEPT-02',
    departmentName: 'Phòng Tài Chính Kế Toán',
    position: 'Kế Toán Viên Công Nợ (Đã thôi việc)',
    role: 'EMPLOYEE',
    managerId: 'EMP-002',
    status: 'RESIGNED',
    contractType: 'DEFINITE_24M',
    contractNumber: 'HDLD-2023-156',
    joinDate: '2023-04-01',
    contractStartDate: '2023-04-01',
    contractEndDate: '2026-08-15',
    bankAccountNumber: '234567890',
    bankName: 'ACB',
    taxCode: '8055661122',
    socialInsuranceNumber: '7923005566',
    numberOfDependents: 0,
    baseSalary: 14000000,
    positionSalary: 2000000,
    lunchAllowance: 730000,
    transportAllowance: 800000,
    phoneAllowance: 0,
    toxicTier: 0,
    annualLeaveTotal: 12,
    annualLeaveUsed: 4,
    annualLeaveCarriedOver: 2,
  },

  // 9. CỘNG TÁC VIÊN HỢP ĐỒNG DỊCH VỤ DÂN SỰ (Thù lao khoán 15tr, khấu trừ 10% thuế, không BHXH/CĐ)
  {
    id: 'EMP-009',
    tenantId: 'TENANT-ASIAFOODS',
    code: 'CTV-001',
    fullName: 'Bùi Quang Huy',
    gender: 'MALE',
    dob: '1991-05-12',
    phone: '0912349988',
    email: 'huy.bui.designer@gmail.com',
    cccd: '079191007788',
    cccdDate: '2022-10-05',
    cccdPlace: 'Cục Cảnh sát QLHC về TTXH',
    address: 'Quận 3, TP.HCM',
    branchId: 'BR-01',
    branchName: 'Trụ Sở Chính TP.HCM',
    departmentId: 'DEPT-06',
    departmentName: 'Phòng Nghiên Cứu & Phát Triển (R&D)',
    position: 'Chuyên Gia Thiết Kế Bao Bì (Hợp đồng dịch vụ)',
    role: 'EMPLOYEE',
    managerId: 'EMP-001',
    status: 'COLLABORATOR',
    contractType: 'CIVIL_SERVICE',
    contractNumber: 'HDDV-2026-015',
    joinDate: '2026-03-01',
    contractStartDate: '2026-03-01',
    contractEndDate: '2026-12-31',
    bankAccountNumber: '19876543210',
    bankName: 'VPBank',
    taxCode: '8077881122',
    socialInsuranceNumber: '',
    numberOfDependents: 0,
    baseSalary: 15000000, // Phí dịch vụ khoán
    positionSalary: 0,
    lunchAllowance: 0,
    transportAllowance: 0,
    phoneAllowance: 0,
    toxicTier: 0,
    annualLeaveTotal: 0,
    annualLeaveUsed: 0,
    annualLeaveCarriedOver: 0,
    isCivilContractor: true,
  },

  // 10. CÔNG NHÂN LƯƠNG TỐI THIỂU VÙNG I MỚI (Áp dụng 5.310.000đ theo Nghị định 293/2025/NĐ-CP)
  {
    id: 'EMP-010',
    tenantId: 'TENANT-ASIAFOODS',
    code: 'AF-010',
    fullName: 'Nguyễn Thị Mai Hoa',
    gender: 'FEMALE',
    dob: '2000-11-20',
    phone: '0966554433',
    email: 'hoa.nguyen@anviet.vn',
    cccd: '079200004455',
    cccdDate: '2023-08-12',
    cccdPlace: 'Cục Cảnh sát QLHC về TTXH',
    address: 'Huyện Củ Chi, TP.HCM',
    branchId: 'BR-02',
    branchName: 'Nhà Máy Chế Biến Thực Phẩm Bình Dương',
    departmentId: 'DEPT-03',
    departmentName: 'Phân Xưởng Đóng Gói',
    position: 'Công Nhân Phụ Ca Đóng Gói (Lương tối thiểu vùng I)',
    role: 'EMPLOYEE',
    status: 'OFFICIAL',
    contractType: 'DEFINITE_12M',
    contractNumber: 'HDLD-2026-442',
    joinDate: '2026-05-01',
    contractStartDate: '2026-05-01',
    contractEndDate: '2027-05-01',
    bankAccountNumber: '6280205998877',
    bankName: 'Agribank',
    taxCode: '8088991122',
    socialInsuranceNumber: '7926004455',
    numberOfDependents: 0,
    baseSalary: 5310000, // Đúng mức tối thiểu vùng I theo Nghị định 293/2025
    positionSalary: 0,
    lunchAllowance: 730000,
    transportAllowance: 500000,
    phoneAllowance: 0,
    toxicTier: 0,
    annualLeaveTotal: 12,
    annualLeaveUsed: 1,
    annualLeaveCarriedOver: 0,
  },

  // 11. KỸ SƯ TĂNG CA ĐỘT BIẾN (OT thường 16h, chủ nhật 24h, lễ 8h, miễn thuế phần chênh lệch OT)
  {
    id: 'EMP-011',
    tenantId: 'TENANT-ASIAFOODS',
    code: 'AF-011',
    fullName: 'Đặng Quốc Bảo',
    gender: 'MALE',
    dob: '1991-08-14',
    phone: '0977334455',
    email: 'bao.dang@anviet.vn',
    cccd: '079091006677',
    cccdDate: '2021-09-22',
    cccdPlace: 'Cục Cảnh sát QLHC về TTXH',
    address: 'Huyện Củ Chi, TP.HCM',
    branchId: 'BR-02',
    branchName: 'Nhà Máy Sản Xuất Củ Chi',
    departmentId: 'DEPT-03',
    departmentName: 'Tổ Bảo Trì & Cơ Điện',
    position: 'Kỹ Sư Trưởng Cơ Điện Nhà Máy',
    role: 'EMPLOYEE',
    status: 'OFFICIAL',
    contractType: 'INDEFINITE',
    contractNumber: 'HDLD-2020-551',
    joinDate: '2020-04-01',
    contractStartDate: '2020-04-01',
    bankAccountNumber: '19033445566778',
    bankName: 'Techcombank',
    taxCode: '8033445566',
    socialInsuranceNumber: '7920006677',
    numberOfDependents: 1,
    baseSalary: 13000000,
    positionSalary: 2000000,
    lunchAllowance: 730000,
    transportAllowance: 1000000,
    phoneAllowance: 500000,
    toxicTier: 1, // 13.000đ/ngày
    annualLeaveTotal: 13,
    annualLeaveUsed: 3,
    annualLeaveCarriedOver: 2,
  },

  // 12. NHÂN VIÊN ĐI MUỘN NHIỀU LẦN (Thiếu 4.5h công, trừ công theo giờ thực tế, không phạt tiền trái luật)
  {
    id: 'EMP-012',
    tenantId: 'TENANT-ASIAFOODS',
    code: 'AF-012',
    fullName: 'Lê Thị Bích Ngọc',
    gender: 'FEMALE',
    dob: '1996-03-28',
    phone: '0938445566',
    email: 'ngoc.le@anviet.vn',
    cccd: '079196001199',
    cccdDate: '2022-04-11',
    cccdPlace: 'Cục Cảnh sát QLHC về TTXH',
    address: 'Quận 12, TP.HCM',
    branchId: 'BR-01',
    branchName: 'Trụ Sở Chính TP.HCM',
    departmentId: 'DEPT-04',
    departmentName: 'Phòng Tiếp Thị & Marketing',
    position: 'Chuyên Viên Nội Dung & Social Media',
    role: 'EMPLOYEE',
    managerId: 'EMP-002',
    status: 'OFFICIAL',
    contractType: 'DEFINITE_24M',
    contractNumber: 'HDLD-2024-211',
    joinDate: '2024-02-01',
    contractStartDate: '2024-02-01',
    bankAccountNumber: '02345678901',
    bankName: 'TPBank',
    taxCode: '8077665544',
    socialInsuranceNumber: '7924001199',
    numberOfDependents: 0,
    baseSalary: 11000000,
    positionSalary: 1000000,
    lunchAllowance: 730000,
    transportAllowance: 600000,
    phoneAllowance: 300000,
    toxicTier: 0,
    annualLeaveTotal: 12,
    annualLeaveUsed: 2,
    annualLeaveCarriedOver: 0,
  },

  // 13. NHÂN VIÊN NGHỈ ỐM DÀI NGÀY (>14 NGÀY ĐƯỢC BHXH TRẢ TRỢ CẤP, THÁNG NÀY MIỄN ĐÓNG BHXH)
  {
    id: 'EMP-013',
    tenantId: 'TENANT-ASIAFOODS',
    code: 'AF-013',
    fullName: 'Trịnh Thu Hà',
    gender: 'FEMALE',
    dob: '1993-07-19',
    phone: '0917665544',
    email: 'ha.trinh@anviet.vn',
    cccd: '079193006655',
    cccdDate: '2021-08-30',
    cccdPlace: 'Cục Cảnh sát QLHC về TTXH',
    address: 'Quận Bình Thạnh, TP.HCM',
    branchId: 'BR-01',
    branchName: 'Trụ Sở Chính TP.HCM',
    departmentId: 'DEPT-02',
    departmentName: 'Phòng Tài Chính Kế Toán',
    position: 'Kế Toán Viên Kho Vận',
    role: 'EMPLOYEE',
    managerId: 'EMP-002',
    status: 'OFFICIAL',
    contractType: 'INDEFINITE',
    contractNumber: 'HDLD-2021-662',
    joinDate: '2021-06-01',
    contractStartDate: '2021-06-01',
    bankAccountNumber: '101867890123',
    bankName: 'VietinBank',
    taxCode: '8044332211',
    socialInsuranceNumber: '7921006655',
    numberOfDependents: 1,
    baseSalary: 12000000,
    positionSalary: 1500000,
    lunchAllowance: 730000,
    transportAllowance: 600000,
    phoneAllowance: 0,
    toxicTier: 0,
    annualLeaveTotal: 13,
    annualLeaveUsed: 1,
    annualLeaveCarriedOver: 0,
  },

  // 14. LẬP TRÌNH VIÊN LÀM VIỆC ONLINE / TỪ XA (Chấm công online tính đủ công, phụ cấp khoán chi)
  {
    id: 'EMP-014',
    tenantId: 'TENANT-ASIAFOODS',
    code: 'AF-014',
    fullName: 'Trần Đức Minh',
    gender: 'MALE',
    dob: '1995-10-08',
    phone: '0908112233',
    email: 'minh.tran@anviet.vn',
    cccd: '079095009988',
    cccdDate: '2022-09-14',
    cccdPlace: 'Cục Cảnh sát QLHC về TTXH',
    address: 'Quận 7, TP.HCM',
    branchId: 'BR-01',
    branchName: 'Trụ Sở Chính TP.HCM',
    departmentId: 'DEPT-07',
    departmentName: 'Phòng Công Nghệ Thông Tin (IT)',
    position: 'Kỹ Sư Phần Mềm Full-Stack (Làm việc Remote)',
    role: 'EMPLOYEE',
    managerId: 'EMP-001',
    status: 'OFFICIAL',
    contractType: 'INDEFINITE',
    contractNumber: 'HDLD-2022-441',
    joinDate: '2022-10-01',
    contractStartDate: '2022-10-01',
    bankAccountNumber: '0987654321098',
    bankName: 'MB Bank',
    taxCode: '8099881122',
    socialInsuranceNumber: '7922009988',
    numberOfDependents: 0,
    baseSalary: 22000000,
    positionSalary: 5000000,
    lunchAllowance: 730000,
    transportAllowance: 0,
    phoneAllowance: 1500000, // Khoán chi viễn thông / internet làm việc từ xa
    toxicTier: 0,
    annualLeaveTotal: 12,
    annualLeaveUsed: 3,
    annualLeaveCarriedOver: 1,
  },

  // 15. CHUYÊN VIÊN ĐỐI NGOẠI NHẬN QUÀ HIỆN VẬT CHỊU THUẾ (Quà 2tr chịu thuế TNCN, không cộng tiền CK)
  {
    id: 'EMP-015',
    tenantId: 'TENANT-ASIAFOODS',
    code: 'AF-015',
    fullName: 'Đinh Ngọc Trâm',
    gender: 'FEMALE',
    dob: '1994-04-30',
    phone: '0915223344',
    email: 'tram.dinh@anviet.vn',
    cccd: '079194005544',
    cccdDate: '2021-10-25',
    cccdPlace: 'Cục Cảnh sát QLHC về TTXH',
    address: 'Quận 1, TP.HCM',
    branchId: 'BR-01',
    branchName: 'Trụ Sở Chính TP.HCM',
    departmentId: 'DEPT-01',
    departmentName: 'Ban Tổng Giám Đốc',
    position: 'Chuyên Viên Đối Ngoại & Quan Hệ Cổ Đông',
    role: 'EMPLOYEE',
    managerId: 'EMP-001',
    status: 'OFFICIAL',
    contractType: 'INDEFINITE',
    contractNumber: 'HDLD-2021-338',
    joinDate: '2021-08-01',
    contractStartDate: '2021-08-01',
    bankAccountNumber: '0071000665544',
    bankName: 'Vietcombank',
    taxCode: '8066554433',
    socialInsuranceNumber: '7921005544',
    numberOfDependents: 0,
    baseSalary: 15000000,
    positionSalary: 3000000,
    lunchAllowance: 730000,
    transportAllowance: 1500000,
    phoneAllowance: 1000000,
    toxicTier: 0,
    nonCashGiftValue: 2000000, // Quà hiện vật phi tiền mặt chịu thuế
    annualLeaveTotal: 13,
    annualLeaveUsed: 2,
    annualLeaveCarriedOver: 2,
  }
];

/**
 * Hàm lấy cấu hình kịch bản tính lương chuẩn xác cho từng nhân viên mẫu
 * Đảm bảo 15 kịch bản sinh dữ liệu nhất quán 100% giữa Bảng Lương và Kiểm Tra Ngược Chuyển Khoản
 */
export function getEmployeePayrollScenario(
  employee: Employee,
  policy: CompanyPolicy,
  month: string
): PayrollCalculationOptions {
  const std = policy.standardWorkDaysPerMonth || 26;

  switch (employee.code) {
    case 'AF-001': // CEO: Lương cao, trần BHXH, thuế bậc 7
      return {
        month,
        actualWorkDays: std,
        scenarioTag: 'CEO_HIGH_TAX',
        scenarioLabel: 'Lãnh đạo thu nhập cao (Chạm trần BHXH 46.8tr, Thuế TNCN bậc 7 cao nhất 35%, 2 NPT)',
      };

    case 'AF-002': // Trưởng phòng NS: Chuẩn chính thức
      return {
        month,
        actualWorkDays: std,
        scenarioTag: 'STANDARD_OFFICE',
        scenarioLabel: 'Chuyên viên chính thức chuẩn (Làm đủ 26 ngày công chuẩn, phụ cấp đầy đủ, thuế bậc 3)',
      };

    case 'AF-003': // C&B: Nghỉ 1 ngày phép năm hưởng nguyên lương
      return {
        month,
        actualWorkDays: std - 1,
        paidLeaveDays: 1,
        scenarioTag: 'ANNUAL_LEAVE_TAKEOVER',
        scenarioLabel: 'Nghỉ phép năm hưởng nguyên lương (25 ngày đi làm + 1 ngày phép năm = 26 ngày tính đủ lương)',
      };

    case 'AF-004': // Thử việc: 85% lương, không BHXH, khấu trừ 10% thuế
      return {
        month,
        actualWorkDays: std,
        scenarioTag: 'PROBATION_10PCT',
        scenarioLabel: 'Nhân viên thử việc (Lương 85%, hợp đồng thử việc riêng không đóng BHXH, khấu trừ 10% thuế TNCN)',
      };

    case 'AF-005': // Ca đêm + Sữa độc hại (hiện vật không cộng tiền chuyển khoản)
      return {
        month,
        actualWorkDays: 24,
        nightHours: 35,
        normalOtHours: 10,
        kpiBonus: 500000,
        scenarioTag: 'NIGHT_TOXIC_IN_KIND',
        scenarioLabel: 'Công nhân ca đêm & độc hại (Phụ trội đêm 30%, bồi dưỡng hiện vật sữa 480k KHÔNG cộng tiền chuyển khoản)',
      };

    case 'AF-006': // Sales: Thưởng KPI 15tr, trừ tạm ứng lương 5tr
      return {
        month,
        actualWorkDays: std,
        kpiBonus: 15000000,
        salaryAdvance: 5000000,
        scenarioTag: 'SALES_KPI_ADVANCE',
        scenarioLabel: 'Trưởng nhóm kinh doanh (Thưởng KPI doanh số 15tr, trừ tạm ứng lương 5tr trực tiếp vào chuyển khoản)',
      };

    case 'AF-007': // Chuyên gia nước ngoài / Không cư trú
      return {
        month,
        actualWorkDays: std,
        scenarioTag: 'NON_RESIDENT_20PCT',
        scenarioLabel: 'Chuyên gia nước ngoài / Không cư trú (Khấu trừ thuế suất phẳng 20% toàn bộ thu nhập chịu thuế, không trừ gia cảnh)',
      };

    case 'AF-008': // Thôi việc giữa tháng: 10 công, thanh lý phép tồn 2 ngày, trừ nợ tài sản 500k
      return {
        month,
        actualWorkDays: 10,
        unpaidDays: 16,
        unusedLeavePayout: Math.round((employee.baseSalary / std) * 2), // 2 ngày phép tồn
        debtDeduction: 500000, // Bồi hoàn tài sản/đồng phục
        scenarioTag: 'OFFBOARDING_SETTLEMENT',
        scenarioLabel: 'Nhân viên nghỉ việc giữa tháng (Thanh lý 10 công, thanh toán 2 ngày phép tồn, trừ công nợ bồi hoàn 500k)',
      };

    case 'AF-009':
    case 'CTV-001': // CTV dịch vụ dân sự
      return {
        month,
        actualWorkDays: std,
        scenarioTag: 'CIVIL_SERVICE_10PCT',
        scenarioLabel: 'Cộng tác viên Hợp đồng dịch vụ dân sự (Thù lao khoán 15tr, khấu trừ 10% thuế, không BHXH/Công đoàn)',
      };

    case 'AF-010': // Công nhân lương tối thiểu vùng I mới
      return {
        month,
        actualWorkDays: std,
        scenarioTag: 'MIN_WAGE_REGION1',
        scenarioLabel: 'Công nhân lương tối thiểu vùng I mới (5.310.000đ theo Nghị định 293/2025/NĐ-CP, đóng BHXH đúng mức, miễn thuế)',
      };

    case 'AF-011': // Kỹ sư OT cao
      return {
        month,
        actualWorkDays: std,
        normalOtHours: 16,
        weekendOtHours: 24,
        holidayOtHours: 0,
        nightOtHours: 8,
        scenarioTag: 'OVERTIME_HIGH',
        scenarioLabel: 'Kỹ sư tăng ca đột biến (OT ngày thường 16h 150%, chủ nhật 24h 200%, đêm lễ 8h 390%, miễn thuế chênh lệch OT)',
      };

    case 'AF-012': // Đi muộn nhiều lần
      return {
        month,
        actualWorkDays: 25.44, // Thiếu 4.5h công = 0.56 ngày
        attendanceBonus: 0, // Mất thưởng chuyên cần do đi muộn 6 lần
        scenarioTag: 'EXCESSIVE_LATE_HOURLY',
        scenarioLabel: 'Nhân viên đi muộn 6 lần trong tháng (Trừ 4.5h công thực tế, không phạt tiền kỷ luật trái luật)',
      };

    case 'AF-013': // Nghỉ ốm > 14 ngày
      return {
        month,
        actualWorkDays: 10,
        sickLeaveDaysInsurance: 16, // > 14 ngày nghỉ ốm
        unpaidDays: 16,
        scenarioTag: 'LONG_SICK_LEAVE_NO_INS',
        scenarioLabel: 'Nhân viên nghỉ ốm dài ngày (Nghỉ ốm 16 ngày hưởng trợ cấp BHXH, tháng này được miễn đóng toàn bộ BHXH/BHYT/BHTN)',
      };

    case 'AF-014': // Remote Online
      return {
        month,
        actualWorkDays: std,
        scenarioTag: 'REMOTE_ONLINE',
        scenarioLabel: 'Lập trình viên làm việc Remote / Online (Chấm công online tính đủ công chuẩn, phụ cấp khoán chi miễn thuế)',
      };

    case 'AF-015': // Nhận quà hiện vật chịu thuế
      return {
        month,
        actualWorkDays: std,
        scenarioTag: 'NON_CASH_GIFT_TAXABLE',
        scenarioLabel: 'Nhân viên nhận quà tặng hiện vật (Quà 2tr phi tiền mặt tính thu nhập chịu thuế, KHÔNG cộng tiền mặt chuyển khoản)',
      };

    default: {
      const isDismissed = employee.status === 'DISMISSED';
      const isResigned = employee.status === 'RESIGNED';
      const exitDate = employee.contractEndDate || (isDismissed ? employee.disciplinaryRecord?.decisionDate : undefined);

      // 1. Kiểm tra trường hợp đã thôi việc / sa thải
      if (isResigned || isDismissed) {
        // Chu kỳ lương 08/2026: 26/07/2026 -> 25/08/2026
        if (!exitDate || exitDate < '2026-07-26') {
          return {
            month,
            actualWorkDays: 0,
            unpaidDays: std,
            scenarioTag: 'RESIGNED_PAST',
            scenarioLabel: `Đã chấm dứt HĐLĐ ngày ${exitDate || 'trước kỳ này'} (Không phát sinh công & lương trong kỳ)`,
          };
        } else {
          // Thôi việc trong kỳ tháng 08/2026
          const exitDay = parseInt(exitDate.split('-')[2] || '12');
          const proratedDays = Math.min(std, Math.max(1, Math.round(exitDay * 0.85)));
          return {
            month,
            actualWorkDays: proratedDays,
            unpaidDays: Math.max(0, std - proratedDays),
            salaryAdvance: employee.debtBalance || 0, // Thu hồi toàn bộ công nợ tồn đọng khi quyết toán
            scenarioTag: 'OFFBOARDING_PRORATED',
            scenarioLabel: `${isDismissed ? 'Sa thải kỷ luật' : 'Thôi việc'} ngày ${exitDate} (Chốt ${proratedDays} công, thu hồi công nợ còn lại)`,
          };
        }
      }

      // 2. Tạm hoãn thực hiện HĐLĐ (Thai sản / Nghĩa vụ quân sự / Nghỉ không lương)
      if (employee.status === 'SUSPENDED') {
        return {
          month,
          actualWorkDays: 0,
          unpaidDays: std,
          scenarioTag: 'SUSPENDED_UNPAID',
          scenarioLabel: 'Tạm hoãn thực hiện HĐLĐ (Nghỉ không lương / Thai sản / Nghĩa vụ quân sự)',
        };
      }

      // 3. Nhân sự chưa đến ngày đi làm
      if (employee.joinDate > '2026-08-25') {
        return {
          month,
          actualWorkDays: 0,
          unpaidDays: std,
          scenarioTag: 'FUTURE_HIRE',
          scenarioLabel: `Chưa đến ngày tiếp nhận (${employee.joinDate})`,
        };
      }

      // 4. Nhân sự mới tiếp nhận trong kỳ lương (26/07 -> 25/08)
      if (employee.joinDate >= '2026-07-26') {
        const joinDay = parseInt(employee.joinDate.split('-')[2] || '01');
        const remainingCalendar = Math.max(1, 26 - joinDay);
        const proratedDays = Math.min(std, Math.max(1, Math.round(remainingCalendar * 0.85)));
        return {
          month,
          actualWorkDays: proratedDays,
          unpaidDays: Math.max(0, std - proratedDays),
          scenarioTag: 'NEW_HIRE_PRORATED',
          scenarioLabel: `Nhân sự mới gia nhập ngày ${employee.joinDate} (Tính công theo tỷ lệ ${proratedDays}/${std} ngày)`,
        };
      }

      // 5. Thử việc
      if (employee.status === 'PROBATION') {
        return {
          month,
          actualWorkDays: std,
          scenarioTag: 'PROBATION_10PCT',
          scenarioLabel: 'Nhân viên thử việc (Lương 85%, hợp đồng thử việc riêng không đóng BHXH, khấu trừ 10% thuế TNCN)',
        };
      }

      // 6. Nhân sự vận hành sản xuất / đóng gói / kho kíp
      const isFactory = employee.departmentName.includes('Đóng Gói') || 
                        employee.departmentName.includes('Nhiệt Hóa') || 
                        employee.departmentName.includes('Cơ Điện') ||
                        employee.departmentName.includes('Kho Vận') ||
                        employee.departmentName.includes('Sơ Chế');
      
      const nightHours = isFactory && (employee.toxicTier && employee.toxicTier >= 2) ? 28 : 0;
      const normalOt = isFactory ? 8 : (employee.role === 'HR_MANAGER' ? 4 : 0);
      const attendanceBonus = 500000;
      const advanceDeduction = employee.debtBalance ? Math.min(2000000, employee.debtBalance) : 0;

      return {
        month,
        actualWorkDays: std,
        nightHours,
        normalOtHours: normalOt,
        attendanceBonus,
        salaryAdvance: advanceDeduction,
        scenarioTag: isFactory ? 'FACTORY_STANDARD' : 'STANDARD_OFFICE',
        scenarioLabel: isFactory
          ? `Sản xuất vận hành (${std} công, ${nightHours > 0 ? `${nightHours}h làm đêm, ` : ''}bồi dưỡng độc hại TT24${advanceDeduction > 0 ? `, khấu trừ tạm ứng ${(advanceDeduction).toLocaleString('vi-VN')}đ` : ''})`
          : `Nhân viên chính thức chuẩn${advanceDeduction > 0 ? ` (Khấu trừ tạm ứng ${(advanceDeduction).toLocaleString('vi-VN')}đ)` : ''}`,
      };
    }
  }
}

// Dữ liệu chấm công minh họa
export const initialAttendanceRecords: AttendanceRecord[] = [
  {
    id: 'ATT-001',
    employeeId: 'EMP-002',
    employeeCode: 'AF-002',
    employeeName: 'Trần Thị Thu Trang',
    departmentName: 'Phòng Nhân Sự',
    date: '2026-08-25',
    shiftCode: 'CA-HC',
    checkIn: '07:55',
    checkOut: '17:35',
    lateMinutes: 0,
    earlyMinutes: 0,
    deductedWorkHours: 0,
    actualWorkHours: 8.0,
    standardWorkHours: 8.0,
    normalOtHours: 0.5,
    weekendOtHours: 0,
    holidayOtHours: 0,
    nightHours: 0,
    nightOtHours: 0,
    source: 'BIOMETRIC_DEVICE',
    status: 'PRESENT',
  },
  {
    id: 'ATT-002',
    employeeId: 'EMP-005',
    employeeCode: 'AF-005',
    employeeName: 'Hoàng Văn Đức',
    departmentName: 'Xưởng Đóng Gói Thực Phẩm',
    date: '2026-08-25',
    shiftCode: 'CA-3',
    checkIn: '21:55',
    checkOut: '06:05',
    lateMinutes: 0,
    earlyMinutes: 0,
    deductedWorkHours: 0,
    actualWorkHours: 7.0,
    standardWorkHours: 7.0,
    normalOtHours: 0,
    weekendOtHours: 0,
    holidayOtHours: 0,
    nightHours: 7.0,
    nightOtHours: 0,
    source: 'BIOMETRIC_DEVICE',
    status: 'PRESENT',
  },
  {
    id: 'ATT-003',
    employeeId: 'EMP-012',
    employeeCode: 'AF-012',
    employeeName: 'Lê Thị Bích Ngọc',
    departmentName: 'Phòng Tiếp Thị & Marketing',
    date: '2026-08-25',
    shiftCode: 'CA-HC',
    checkIn: '08:45',
    checkOut: '17:00',
    lateMinutes: 45,
    earlyMinutes: 0,
    deductedWorkHours: 1.0,
    actualWorkHours: 7.0,
    standardWorkHours: 8.0,
    normalOtHours: 0,
    weekendOtHours: 0,
    holidayOtHours: 0,
    nightHours: 0,
    nightOtHours: 0,
    source: 'WEB_PORTAL',
    status: 'LATE',
    notes: 'Đi muộn 45 phút do kẹt xe cầu Bình Triệu',
  },
  {
    id: 'ATT-004',
    employeeId: 'EMP-014',
    employeeCode: 'AF-014',
    employeeName: 'Trần Đức Minh',
    departmentName: 'Phòng Công Nghệ Thông Tin (IT)',
    date: '2026-08-25',
    shiftCode: 'CA-HC',
    checkIn: '08:00',
    checkOut: '17:30',
    lateMinutes: 0,
    earlyMinutes: 0,
    deductedWorkHours: 0,
    actualWorkHours: 8.0,
    standardWorkHours: 8.0,
    normalOtHours: 0.5,
    weekendOtHours: 0,
    holidayOtHours: 0,
    nightHours: 0,
    nightOtHours: 0,
    source: 'MOBILE_GPS_FACE',
    status: 'ONLINE_WORK',
    notes: 'Chấm công WFH (Làm việc từ xa) hợp lệ qua định vị GPS',
  }
];

export const initialRequests: WorkflowRequest[] = [
  {
    id: 'REQ-01',
    tenantId: 'TENANT-ASIAFOODS',
    employeeId: 'EMP-003',
    employeeName: 'Lê Hoàng Nam',
    departmentName: 'Phòng Nhân Sự',
    type: 'LEAVE',
    title: 'Đơn xin nghỉ phép năm 1 ngày',
    reason: 'Giải quyết việc gia đình cá nhân',
    startDate: '2026-08-15',
    endDate: '2026-08-15',
    durationDays: 1,
    leaveType: 'ANNUAL',
    status: 'APPROVED',
    currentApproverId: 'EMP-002',
    currentApproverName: 'Trần Thị Thu Trang',
    approvalHistory: [
      {
        step: 1,
        approverName: 'Trần Thị Thu Trang',
        action: 'APPROVED',
        comment: 'Đã bố trí người trực thay, duyệt nghỉ phép hưởng lương.',
        timestamp: '2026-08-14 16:30',
      }
    ],
    createdAt: '2026-08-14 10:15',
  },
  {
    id: 'REQ-02',
    tenantId: 'TENANT-ASIAFOODS',
    employeeId: 'EMP-006',
    employeeName: 'Vũ Đình Trọng',
    departmentName: 'Khối Kinh Doanh Toàn Quốc',
    type: 'SALARY_ADVANCE',
    title: 'Đề nghị tạm ứng lương giữa kỳ',
    reason: 'Tạm ứng công tác phí thị trường miền Tây',
    requestedAmount: 5000000,
    status: 'APPROVED',
    currentApproverId: 'EMP-001',
    currentApproverName: 'Nguyễn Văn Hùng',
    approvalHistory: [
      {
        step: 1,
        approverName: 'Trần Thị Thu Trang',
        action: 'FORWARDED',
        comment: 'Đủ điều kiện tạm ứng, chuyển TGĐ phê duyệt.',
        timestamp: '2026-08-10 11:00',
      },
      {
        step: 2,
        approverName: 'Nguyễn Văn Hùng',
        action: 'APPROVED',
        comment: 'Đồng ý tạm ứng 5.000.000đ, kế toán trừ vào kỳ lương tháng 8.',
        timestamp: '2026-08-10 14:20',
      }
    ],
    createdAt: '2026-08-10 09:30',
  }
];

export const initialOffboardings: OffboardingRecord[] = [
  {
    id: 'OFF-001',
    tenantId: 'TENANT-ASIAFOODS',
    employeeId: 'EMP-008',
    employeeCode: 'AF-008',
    employeeName: 'Đỗ Thị Thu Hiền',
    departmentName: 'Phòng Tài Chính Kế Toán',
    position: 'Kế Toán Viên Công Nợ (Đã thôi việc)',
    resignationDate: '2026-07-15',
    lastWorkingDate: '2026-08-15',
    reason: 'Thay đổi định hướng cá nhân và chuyển nơi cư trú',
    handoverWorkCompleted: true,
    handoverAssetCompleted: true,
    handoverItAccountCompleted: true,
    handoverFinanceCompleted: true,
    remainingDaysSalary: 5384615,
    remainingLeaveDays: 2,
    remainingLeavePay: 1076923,
    severancePay: 0,
    deductionDebt: 500000,
    netSettlementAmount: 5961538,
    paymentDeadlineOption: 'WITHIN_14_DAYS',
    status: 'COMPLETED',
  },
  {
    id: 'OFF-002',
    tenantId: 'TENANT-ASIAFOODS',
    employeeId: 'AV-0422',
    employeeCode: 'AV-0422',
    employeeName: 'Tạ Quang N',
    departmentName: 'Phòng Kỹ Thuật Cơ Điện',
    position: 'Kỹ Sư Vận Hành Thiết Bị Áp Lực',
    resignationDate: '2026-08-20',
    lastWorkingDate: '2026-09-15',
    reason: 'Xin chấm dứt hợp đồng lao động trước hạn (Có cam kết đào tạo)',
    handoverWorkCompleted: true,
    handoverAssetCompleted: true,
    handoverItAccountCompleted: true,
    handoverFinanceCompleted: false,
    remainingDaysSalary: 7200000,
    remainingLeaveDays: 3,
    remainingLeavePay: 1250000,
    severancePay: 0,
    deductionDebt: 0,
    netSettlementAmount: 4450000,
    paymentDeadlineOption: 'WITHIN_14_DAYS',
    status: 'PENDING',
  }
];

export const jobDescriptionsLibrary: JobDescription[] = [
  {
    id: 'JD-01',
    title: 'Kỹ Sư Công Nghệ Thực Phẩm (R&D)',
    departmentName: 'Phòng Nghiên Cứu & Phát Triển (R&D)',
    salaryRange: '15.000.000 - 25.000.000 VNĐ',
    minExperienceYears: 2,
    summary: 'Nghiên cứu phát triển công thức sản phẩm mới và kiểm định chất lượng ATTP.',
    keyResponsibilities: [
      'Nghiên cứu công thức và cải tiến bao bì sản phẩm',
      'Đánh giá chất lượng nguyên vật liệu đầu vào',
      'Tuân thủ tiêu chuẩn ISO 22000 và HACCP',
    ],
    requiredSkills: ['ISO 22000', 'HACCP', 'Food Science', 'Phân tích cảm quan'],
  },
  {
    id: 'JD-02',
    title: 'Chuyên Viên C&B (Tiền Lương & Phúc Lợi)',
    departmentName: 'Phòng Nhân Sự',
    salaryRange: '14.000.000 - 20.000.000 VNĐ',
    minExperienceYears: 3,
    summary: 'Phụ trách toàn diện tính lương, BHXH, thuế TNCN và danh sách chuyển khoản ngân hàng.',
    keyResponsibilities: [
      'Tổng hợp bảng chấm công và tính lương hàng tháng',
      'Kê khai BHXH điện tử và quyết toán thuế TNCN',
      'Lập lệnh chi lương chuyển khoản và đối chiếu ngân hàng',
    ],
    requiredSkills: ['Luật Lao Động 2019', 'Thuế TNCN', 'BHXH', 'Excel nâng cao', 'Chi hộ ngân hàng'],
  },
  {
    id: 'JD-03',
    title: 'Trưởng Nhóm Kinh Doanh Bán Lẻ (Sales Lead)',
    departmentName: 'Khối Kinh Doanh Toàn Quốc',
    salaryRange: '18.000.000 - 35.000.000 VNĐ',
    minExperienceYears: 3,
    summary: 'Mở rộng kênh phân phối GT/MT và quản lý đội ngũ nhân viên thị trường.',
    keyResponsibilities: [
      'Xây dựng kế hoạch doanh số tháng/quý',
      'Quản lý và hỗ trợ NPP/Đại lý khu vực',
      'Đào tạo và thúc đẩy KPI đội ngũ bán hàng',
    ],
    requiredSkills: ['FMCG Sales', 'Quản lý đại lý', 'Đàm phán', 'Kỹ năng lãnh đạo'],
  }
];

export const initialCandidates = [
  {
    id: 'CAND-01',
    tenantId: 'TENANT-ASIAFOODS',
    fullName: 'Hoàng Văn Nam',
    email: 'nam.hoang.rd@gmail.com',
    phone: '0938112233',
    positionApplied: 'Kỹ Sư Công Nghệ Thực Phẩm (R&D)',
    departmentName: 'Phòng Nghiên Cứu & Phát Triển (R&D)',
    appliedDate: '2026-08-10',
    stage: 'INTERVIEWING' as const,
    cvUrl: '',
    cvSummaryText: 'Cử nhân Công nghệ thực phẩm ĐH Bách Khoa, 3 năm kinh nghiệm R&D đồ hộp.',
    skills: ['HACCP', 'ISO 22000', 'Food Science'],
    experienceYears: 3,
    aiMatchScore: 88,
    aiReviewNotes: 'Rất phù hợp kinh nghiệm ngành thực phẩm, có chứng chỉ HACCP.',
    expectedSalary: 18000000,
    offeredSalary: 17000000,
  }
];

export const initialKpis = [];

export const initialCourses: TrainingCourse[] = [
  {
    id: 'CRS-01',
    tenantId: 'TENANT-ASIAFOODS',
    title: 'An Toàn Vệ Sinh Lao Động & PCCC Nhà Máy',
    category: 'SAFETY_LABOR',
    description: 'Quy chuẩn an toàn khi vận hành máy móc thiết bị và phòng cháy chữa cháy.',
    durationHours: 4,
    isRequired: true,
    totalLessons: 6,
    enrolledEmployees: 45,
    passPercentage: 92,
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    minRequiredMinutes: 15,
    actualWatchedMinutes: 18,
    watchCount: 3,
    isWatchRequirementMet: true,
  },
  {
    id: 'CRS-02',
    tenantId: 'TENANT-ASIAFOODS',
    title: 'HACCP & Tiêu Chuẩn Vệ Sinh An Toàn Thực Phẩm',
    category: 'ONBOARDING',
    description: 'Nguyên tắc kiểm soát điểm giới hạn tới hạn trong chế biến thực phẩm.',
    durationHours: 6,
    isRequired: true,
    totalLessons: 8,
    enrolledEmployees: 60,
    passPercentage: 88,
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    minRequiredMinutes: 20,
    actualWatchedMinutes: 12,
    watchCount: 1,
    isWatchRequirementMet: false,
  }
];

export const initialAccountingEntries: AccountingJournalEntry[] = [
  {
    id: 'ACC-PAY-01',
    date: '2026-08-25',
    description: 'Trích tính chi phí tiền lương tháng 2026-08 cho Phân Xưởng Đóng Gói',
    departmentName: 'Phân Xưởng Đóng Gói',
    debitAccount: '622',
    creditAccount: '334',
    amount: 185000000,
  },
  {
    id: 'ACC-INS-01',
    date: '2026-08-25',
    description: 'Trích bảo hiểm bắt buộc & KPCĐ (23.5%) tính vào chi phí Phân Xưởng Đóng Gói',
    departmentName: 'Phân Xưởng Đóng Gói',
    debitAccount: '622',
    creditAccount: '338',
    amount: 43475000,
  },
  {
    id: 'ACC-PAY-02',
    date: '2026-08-25',
    description: 'Trích tính chi phí tiền lương tháng 2026-08 cho Phân Xưởng Chế Biến & Nhiệt Hóa',
    departmentName: 'Phân Xưởng Chế Biến & Nhiệt Hóa',
    debitAccount: '622',
    creditAccount: '334',
    amount: 245000000,
  },
  {
    id: 'ACC-INS-02',
    date: '2026-08-25',
    description: 'Trích bảo hiểm bắt buộc & KPCĐ (23.5%) tính vào chi phí Phân Xưởng Chế Biến',
    departmentName: 'Phân Xưởng Chế Biến & Nhiệt Hóa',
    debitAccount: '622',
    creditAccount: '338',
    amount: 57575000,
  },
  {
    id: 'ACC-PAY-03',
    date: '2026-08-25',
    description: 'Trích tính chi phí tiền lương tháng 2026-08 cho Phòng Quản Lý Chất Lượng QA/QC',
    departmentName: 'Phòng Quản Lý Chất Lượng QA/QC',
    debitAccount: '627',
    creditAccount: '334',
    amount: 78000000,
  },
  {
    id: 'ACC-INS-03',
    date: '2026-08-25',
    description: 'Trích bảo hiểm bắt buộc & KPCĐ (23.5%) tính vào chi phí Quản Lý Chất Lượng',
    departmentName: 'Phòng Quản Lý Chất Lượng QA/QC',
    debitAccount: '627',
    creditAccount: '338',
    amount: 18330000,
  },
  {
    id: 'ACC-PAY-04',
    date: '2026-08-25',
    description: 'Trích tính chi phí tiền lương tháng 2026-08 cho Khối Kinh Doanh & Tiếp Thị',
    departmentName: 'Khối Kinh Doanh & Tiếp Thị',
    debitAccount: '641',
    creditAccount: '334',
    amount: 135000000,
  },
  {
    id: 'ACC-INS-04',
    date: '2026-08-25',
    description: 'Trích bảo hiểm bắt buộc & KPCĐ (23.5%) tính vào chi phí Bán Hàng',
    departmentName: 'Khối Kinh Doanh & Tiếp Thị',
    debitAccount: '641',
    creditAccount: '338',
    amount: 31725000,
  },
  {
    id: 'ACC-PAY-05',
    date: '2026-08-25',
    description: 'Trích tính chi phí tiền lương tháng 2026-08 cho Ban Tổng Giám Đốc & Khối Văn Phòng',
    departmentName: 'Ban Giám Đốc & Văn Phòng',
    debitAccount: '642',
    creditAccount: '334',
    amount: 165000000,
  },
  {
    id: 'ACC-INS-05',
    date: '2026-08-25',
    description: 'Trích bảo hiểm bắt buộc & KPCĐ (23.5%) tính vào chi phí QLDN',
    departmentName: 'Ban Giám Đốc & Văn Phòng',
    debitAccount: '642',
    creditAccount: '338',
    amount: 38775000,
  },
  {
    id: 'ACC-NET-01',
    date: '2026-08-28',
    description: 'Lệnh chuyển khoản ngân hàng thanh toán lương thực lĩnh (Net) tháng 2026-08',
    departmentName: 'Toàn Doanh Nghiệp',
    debitAccount: '334',
    creditAccount: '112',
    amount: 685000000,
  }
];

export const initialPersonnelChanges: PersonnelChange[] = [
  {
    id: 'CHG-01',
    code: 'BDNS-2026-001',
    tenantId: 'TENANT-ASIAFOODS',
    employeeId: 'EMP-003',
    employeeCode: 'AF-003',
    employeeName: 'Lê Hoàng Nam',
    departmentName: 'Phòng Nhân Sự',
    currentPosition: 'Chuyên Viên C&B',
    type: 'SALARY_ADJUSTMENT',
    title: 'Điều chỉnh nâng bậc lương cơ bản và bổ sung phụ cấp trách nhiệm C&B',
    reason: 'Đánh giá hoàn thành xuất sắc KPI 6 tháng đầu năm, tiếp nhận phụ trách thêm phần mềm chấm công GPS và quyết toán thuế.',
    effectiveDate: '2026-07-01',
    previousData: {
      baseSalary: 14000000,
      positionSalary: 2000000,
      lunchAllowance: 730000,
      transportAllowance: 500000,
      phoneAllowance: 300000,
      toxicTier: 0,
      position: 'Chuyên Viên C&B',
      departmentName: 'Phòng Nhân Sự',
      branchName: 'VP Điều Hành TP.HCM',
      status: 'OFFICIAL'
    },
    proposedData: {
      baseSalary: 16000000,
      positionSalary: 3000000,
      lunchAllowance: 730000,
      transportAllowance: 800000,
      phoneAllowance: 500000,
      toxicTier: 0,
      position: 'Chuyên Viên C&B (Tiền Lương & Phúc Lợi)',
      departmentName: 'Phòng Nhân Sự',
      branchName: 'VP Điều Hành TP.HCM',
      status: 'OFFICIAL'
    },
    status: 'APPLIED',
    proposedBy: 'Trần Thị Thu Thảo (Trưởng Phòng HCNS)',
    proposedDate: '2026-06-20',
    hrReviewedBy: 'Trần Thị Thu Thảo',
    hrReviewedDate: '2026-06-22',
    hrNotes: 'Đã đối chiếu quỹ lương phòng HCNS 2026, trong hạn mức định biên lương được duyệt.',
    approvedBy: 'Nguyễn Văn Hùng (Tổng Giám Đốc)',
    approvedDate: '2026-06-25',
    approvalNotes: 'Đồng ý nâng lương bậc 2 từ ngày 01/07/2026.',
    decisionNumber: 'QD-071/2026/QD-AV',
    decisionDate: '2026-06-26',
    signerName: 'Nguyễn Văn Hùng',
    signerTitle: 'Tổng Giám Đốc',
    isAppliedToPayroll: true,
    isAppliedToProfile: true,
    appliedDate: '2026-07-01'
  },
  {
    id: 'CHG-02',
    code: 'BDNS-2026-002',
    tenantId: 'TENANT-ASIAFOODS',
    employeeId: 'EMP-005',
    employeeCode: 'AF-005',
    employeeName: 'Trần Thị Bích Vân',
    departmentName: 'Phân Xưởng Đóng Gói',
    currentPosition: 'Tổ Trưởng Sản Xuất',
    type: 'PROMOTION_APPOINTMENT',
    title: 'Bổ nhiệm giữ chức vụ Phó Quản Đốc Phân Xưởng Đóng Gói Nhà Máy Bình Dương',
    reason: 'Quy hoạch cán bộ nguồn, đáp ứng năng lực quản lý dây chuyền đóng gói tự động đạt chứng chỉ HACCP.',
    effectiveDate: '2026-09-01',
    previousData: {
      baseSalary: 11000000,
      positionSalary: 1500000,
      lunchAllowance: 730000,
      transportAllowance: 400000,
      phoneAllowance: 200000,
      toxicTier: 1,
      position: 'Tổ Trưởng Sản Xuất',
      departmentName: 'Phân Xưởng Đóng Gói',
      branchName: 'Nhà Máy Bình Dương',
      status: 'OFFICIAL'
    },
    proposedData: {
      baseSalary: 14500000,
      positionSalary: 3500000,
      lunchAllowance: 730000,
      transportAllowance: 800000,
      phoneAllowance: 500000,
      toxicTier: 1,
      position: 'Phó Quản Đốc Phân Xưởng',
      departmentName: 'Phân Xưởng Đóng Gói',
      branchName: 'Nhà Máy Bình Dương',
      status: 'OFFICIAL'
    },
    status: 'DECISION_ISSUED',
    proposedBy: 'Nguyễn Văn Thành (Giám Đốc Nhà Máy)',
    proposedDate: '2026-08-15',
    hrReviewedBy: 'Trần Thị Thu Thảo',
    hrReviewedDate: '2026-08-18',
    hrNotes: 'Đạt yêu cầu sát hạch quản lý cấp trung, hồ sơ năng lực đầy đủ.',
    approvedBy: 'Nguyễn Văn Hùng (Tổng Giám Đốc)',
    approvedDate: '2026-08-22',
    approvalNotes: 'Phê duyệt bổ nhiệm theo tờ trình số 12/TTr-NMBD.',
    decisionNumber: 'QD-082/2026/QD-AV',
    decisionDate: '2026-08-25',
    signerName: 'Nguyễn Văn Hùng',
    signerTitle: 'Tổng Giám Đốc',
    isAppliedToPayroll: false,
    isAppliedToProfile: false
  },
  {
    id: 'CHG-03',
    code: 'BDNS-2026-003',
    tenantId: 'TENANT-ASIAFOODS',
    employeeId: 'EMP-007',
    employeeCode: 'AF-007',
    employeeName: 'Phạm Quốc Bảo',
    departmentName: 'Phòng Kỹ Thuật & Cơ Điện',
    currentPosition: 'Kỹ Sư Cơ Điện',
    type: 'WORKPLACE_RELOCATION',
    title: 'Điều chuyển nơi làm việc từ VP Điều Hành TP.HCM sang Nhà Máy Long An',
    reason: 'Triển khai lắp đặt và chuyển giao công nghệ dây chuyền chiết rót công suất 12.000 chai/giờ.',
    effectiveDate: '2026-09-01',
    previousData: {
      baseSalary: 13500000,
      positionSalary: 2000000,
      lunchAllowance: 730000,
      transportAllowance: 600000,
      phoneAllowance: 300000,
      toxicTier: 0,
      position: 'Kỹ Sư Cơ Điện',
      departmentName: 'Phòng Kỹ Thuật & Cơ Điện',
      branchName: 'VP Điều Hành TP.HCM',
      status: 'OFFICIAL'
    },
    proposedData: {
      baseSalary: 13500000,
      positionSalary: 2000000,
      lunchAllowance: 730000,
      transportAllowance: 1500000,
      phoneAllowance: 500000,
      toxicTier: 1,
      position: 'Kỹ Sư Cơ Điện - Trưởng Nhóm Dự Án Long An',
      departmentName: 'Phòng Kỹ Thuật & Cơ Điện',
      branchName: 'Nhà Máy Long An',
      status: 'OFFICIAL'
    },
    status: 'APPROVED',
    proposedBy: 'Lê Minh Tuấn (Trưởng Phòng Kỹ Thuật)',
    proposedDate: '2026-08-20',
    hrReviewedBy: 'Trần Thị Thu Thảo',
    hrReviewedDate: '2026-08-22',
    hrNotes: 'Bổ sung phụ cấp công tác xa nhà 1.500.000đ/tháng theo quy chế tài chính.',
    approvedBy: 'Nguyễn Văn Hùng (Tổng Giám Đốc)',
    approvedDate: '2026-08-26',
    approvalNotes: 'Đồng ý điều chuyển thời hạn 12 tháng.',
    decisionNumber: '',
    isAppliedToPayroll: false,
    isAppliedToProfile: false
  },
  {
    id: 'CHG-04',
    code: 'BDNS-2026-004',
    tenantId: 'TENANT-ASIAFOODS',
    employeeId: 'EMP-012',
    employeeCode: 'AF-012',
    employeeName: 'Nguyễn Minh Quân',
    departmentName: 'Phòng Kinh Doanh & Tiếp Thị',
    currentPosition: 'Nhân Viên Kinh Doanh B2B',
    type: 'OFFICIAL_CONVERSION',
    title: 'Tiếp nhận chính thức và ký Hợp đồng lao động xác định thời hạn 12 tháng',
    reason: 'Hết thời gian thử việc 60 ngày, kết quả đánh giá thử việc đạt 94/100 điểm, vượt chỉ tiêu doanh số 115%.',
    effectiveDate: '2026-09-01',
    previousData: {
      baseSalary: 8500000,
      positionSalary: 1000000,
      lunchAllowance: 730000,
      transportAllowance: 500000,
      phoneAllowance: 300000,
      toxicTier: 0,
      position: 'Nhân Viên Kinh Doanh B2B (Thử Việc)',
      departmentName: 'Phòng Kinh Doanh & Tiếp Thị',
      branchName: 'VP Điều Hành TP.HCM',
      status: 'PROBATION'
    },
    proposedData: {
      baseSalary: 10000000,
      positionSalary: 2500000,
      lunchAllowance: 730000,
      transportAllowance: 800000,
      phoneAllowance: 500000,
      toxicTier: 0,
      position: 'Chuyên Viên Kinh Doanh B2B',
      departmentName: 'Phòng Kinh Doanh & Tiếp Thị',
      branchName: 'VP Điều Hành TP.HCM',
      status: 'OFFICIAL'
    },
    status: 'HR_REVIEWED',
    proposedBy: 'Vũ Đình Hải (Giám Đốc Kinh Doanh)',
    proposedDate: '2026-08-24',
    hrReviewedBy: 'Trần Thị Thu Thảo',
    hrReviewedDate: '2026-08-26',
    hrNotes: 'Hồ sơ đầy đủ, chuyển từ HĐ Thử việc sang HĐLĐ 12 tháng, bắt đầu tham gia đóng BHXH bắt buộc từ tháng 09/2026.',
    isAppliedToPayroll: false,
    isAppliedToProfile: false
  },
  {
    id: 'CHG-05',
    code: 'BDNS-2026-005',
    tenantId: 'TENANT-ASIAFOODS',
    employeeId: 'EMP-018',
    employeeCode: 'AF-018',
    employeeName: 'Hoàng Văn Thái',
    departmentName: 'Kho Vận & Logistics',
    currentPosition: 'Nhân Viên Lái Xe Nâng',
    type: 'BENEFITS_SHIFT_CHANGE',
    title: 'Điều chỉnh nâng mức phụ cấp độc hại Mức 2 và chuyển sang Ca 12h',
    reason: 'Khu vực kho lạnh bảo quản nguyên liệu hóa chất có điều kiện lao động loại IV theo kết quả đo kiểm môi trường lao động.',
    effectiveDate: '2026-09-01',
    previousData: {
      baseSalary: 8200000,
      positionSalary: 1000000,
      lunchAllowance: 730000,
      transportAllowance: 400000,
      phoneAllowance: 0,
      toxicTier: 1,
      position: 'Nhân Viên Lái Xe Nâng',
      departmentName: 'Kho Vận & Logistics',
      branchName: 'Nhà Máy Bình Dương',
      status: 'OFFICIAL'
    },
    proposedData: {
      baseSalary: 8200000,
      positionSalary: 1000000,
      lunchAllowance: 730000,
      transportAllowance: 400000,
      phoneAllowance: 0,
      toxicTier: 2,
      position: 'Nhân Viên Lái Xe Nâng (Kho Lạnh)',
      departmentName: 'Kho Vận & Logistics',
      branchName: 'Nhà Máy Bình Dương',
      status: 'OFFICIAL'
    },
    status: 'PROPOSED',
    proposedBy: 'Đặng Ngọc Tân (Trưởng Bộ Phận Kho Vận)',
    proposedDate: '2026-08-27',
    isAppliedToPayroll: false,
    isAppliedToProfile: false
  }
];


export const initialDailyReports: DailyWorkReportItem[] = [
  {
    id: 'DWR-2026-001',
    tenantId: 'TENANT-ASIAFOODS',
    employeeId: 'EMP-003',
    employeeCode: 'AF-003',
    employeeName: 'Lê Hoàng Nam',
    departmentName: 'Phòng Nhân Sự',
    positionName: 'Chuyên Viên C&B',
    isDeptHead: false,
    date: '2026-09-08',
    taskTitle: 'Đối soát dữ liệu bảng công máy chấm công vân tay & khóa số liệu tháng 08',
    taskDescription: 'Rà soát 250 bản ghi chấm công, đối soát các trường hợp đi muộn về sớm có giải trình hợp lệ, chốt giờ làm thêm OT chuẩn Điều 107.',
    spentHours: 4.5,
    targetType: 'KPI_METRIC',
    kpiId: 'KPI-01',
    kpiName: 'Chốt bảng công và chi trả lương đúng hạn trước ngày 05 hàng tháng',
    kpiProgressContribution: 25,
    status: 'COMPLETED',
    managerFeedback: 'Làm tốt, đối soát số liệu khớp 100% không phát sinh khiếu nại.',
    managerRating: 5,
    createdAt: '2026-09-08T17:15:00Z'
  },
  {
    id: 'DWR-2026-002',
    tenantId: 'TENANT-ASIAFOODS',
    employeeId: 'EMP-003',
    employeeCode: 'AF-003',
    employeeName: 'Lê Hoàng Nam',
    departmentName: 'Phòng Nhân Sự',
    positionName: 'Chuyên Viên C&B',
    isDeptHead: false,
    date: '2026-09-08',
    taskTitle: 'Rà soát danh sách 15 hợp đồng lao động xác định thời hạn sắp đến hạn',
    taskDescription: 'Soạn thảo phụ lục gia hạn HĐLĐ và thông báo trước 30 ngày cho các nhân sự khối nhà máy theo đúng Điều 20 Bộ luật Lao động 2019.',
    spentHours: 3.5,
    targetType: 'KPI_METRIC',
    kpiId: 'KPI-02',
    kpiName: 'Tuân thủ 100% thời hạn pháp lý hợp đồng và hồ sơ lao động theo BLLĐ',
    kpiProgressContribution: 20,
    status: 'COMPLETED',
    managerFeedback: 'Đã ký duyệt dự thảo phụ lục.',
    managerRating: 5,
    createdAt: '2026-09-08T17:45:00Z'
  },
  {
    id: 'DWR-2026-003',
    tenantId: 'TENANT-ASIAFOODS',
    employeeId: 'EMP-004',
    employeeCode: 'AF-004',
    employeeName: 'Phạm Thu Hà',
    departmentName: 'Phòng Nhân Sự',
    positionName: 'Chuyên Viên Tuyển Dụng',
    isDeptHead: false,
    date: '2026-09-08',
    taskTitle: 'Sàng lọc CV và phỏng vấn vòng 1 vị trí Kỹ Sư R&D Thực Phẩm',
    taskDescription: 'Duyệt 18 CV trên hệ thống ATS AI, tiến hành phỏng vấn trực tiếp 3 ứng viên xuất sắc đạt điểm match > 85%.',
    spentHours: 5.0,
    targetType: 'KPI_METRIC',
    kpiId: 'KPI-03',
    kpiName: 'Đáp ứng 95% định biên nhân sự chất lượng cao đúng tiến độ kế hoạch',
    kpiProgressContribution: 15,
    status: 'COMPLETED',
    managerFeedback: 'Chọn được 1 ứng viên tiềm năng để Trưởng phòng phỏng vấn vòng 2.',
    managerRating: 4,
    createdAt: '2026-09-08T16:30:00Z'
  },
  {
    id: 'DWR-2026-004',
    tenantId: 'TENANT-ASIAFOODS',
    employeeId: 'EMP-004',
    employeeCode: 'AF-004',
    employeeName: 'Phạm Thu Hà',
    departmentName: 'Phòng Nhân Sự',
    positionName: 'Chuyên Viên Tuyển Dụng',
    isDeptHead: false,
    date: '2026-09-08',
    taskTitle: 'Cập nhật hồ sơ lưu trữ nhân viên mới nhận việc đầu tuần',
    taskDescription: 'Lưu trữ bản cứng lý lịch tư pháp, giấy khám sức khỏe và cấp thẻ từ ra vào nhà máy.',
    spentHours: 2.5,
    targetType: 'JOB_DESCRIPTION',
    jdDutyId: 'JD-HR-01',
    jdDutyName: 'Tiếp nhận nhân sự mới và quản lý hồ sơ nhân viên',
    status: 'COMPLETED',
    createdAt: '2026-09-08T17:00:00Z'
  },
  {
    id: 'DWR-2026-005',
    tenantId: 'TENANT-ASIAFOODS',
    employeeId: 'EMP-002',
    employeeCode: 'AF-002',
    employeeName: 'Trần Thị Mai',
    departmentName: 'Phòng Nhân Sự',
    positionName: 'Trưởng Phòng Nhân Sự',
    isDeptHead: true,
    date: '2026-09-08',
    taskTitle: 'Chủ trì họp rà soát Báo cáo Tai Nạn Lao Động & ATVSLĐ gửi Sở LĐ-TB&XH',
    taskDescription: 'Làm việc với bộ phận HSE nhà máy, hoàn thiện số liệu 6 tháng và trình Tổng Giám Đốc ký số nộp cơ quan nhà nước.',
    spentHours: 4.0,
    targetType: 'KPI_METRIC',
    kpiId: 'KPI-04',
    kpiName: 'Không để xảy ra bất kỳ khoản phạt vi phạm hành chính nào từ cơ quan quản lý',
    kpiProgressContribution: 30,
    status: 'COMPLETED',
    managerFeedback: 'Tổng Giám Đốc đã ký duyệt số.',
    managerRating: 5,
    createdAt: '2026-09-08T18:00:00Z'
  },
  {
    id: 'DWR-2026-006',
    tenantId: 'TENANT-ASIAFOODS',
    employeeId: 'EMP-005',
    employeeCode: 'AF-005',
    employeeName: 'Đỗ Văn Cường',
    departmentName: 'Phân Xưởng Đóng Gói',
    positionName: 'Kỹ Thuật Viên Vận Hành Máy',
    isDeptHead: false,
    date: '2026-09-08',
    taskTitle: 'Bảo trì máy đóng gói hút chân không Line 1 và hiệu chuẩn nhiệt độ hàn',
    taskDescription: 'Kiểm tra thanh hàn nhiệt, thay thế lưỡi dao cắt bao bì bị mòn, khắc phục lỗi rò rỉ khí nén.',
    spentHours: 6.0,
    targetType: 'KPI_METRIC',
    kpiId: 'KPI-05',
    kpiName: 'Tỷ lệ máy móc sẵn sàng hoạt động đạt trên 98.5%, sự cố dừng máy < 2h',
    kpiProgressContribution: 20,
    status: 'IN_PROGRESS',
    blockerReason: 'Đang chờ bộ phận kho cấp bổ sung 02 ron cao su chịu nhiệt chịu áp suất cao.',
    managerFeedback: 'Đã báo kho vật tư xuất gấp trong sáng mai.',
    managerRating: 4,
    createdAt: '2026-09-08T16:45:00Z'
  }
];
