import { TrainingCourse } from "../types/hrm";

export const comprehensiveCourses: TrainingCourse[] = [
  {
    "id": "CRS-01",
    "tenantId": "TENANT-ASIAFOODS",
    "title": "An Toàn Vệ Sinh Lao Động & PCCC Nhà Máy Chuẩn Quốc Gia",
    "category": "SAFETY_LABOR",
    "description": "Khóa học đào tạo thực hành chuyên sâu chuẩn hóa năng lực vận hành tại An Việt Manufacturing.",
    "durationHours": 2,
    "isRequired": true,
    "totalLessons": 4,
    "enrolledEmployees": 40,
    "passPercentage": 82,
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    "minRequiredMinutes": 10,
    "actualWatchedMinutes": 7,
    "watchCount": 1,
    "isWatchRequirementMet": false
  },
  {
    "id": "CRS-02",
    "tenantId": "TENANT-ASIAFOODS",
    "title": "Quy Tắc Vận Hành Thiết Bị Áp Lực & Nồi Hơi An Toàn",
    "category": "ONBOARDING",
    "description": "Khóa học đào tạo thực hành chuyên sâu chuẩn hóa năng lực vận hành tại An Việt Manufacturing.",
    "durationHours": 3,
    "isRequired": false,
    "totalLessons": 5,
    "enrolledEmployees": 52,
    "passPercentage": 83,
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    "minRequiredMinutes": 11,
    "actualWatchedMinutes": 12,
    "watchCount": 3,
    "isWatchRequirementMet": true
  },
  {
    "id": "CRS-03",
    "tenantId": "TENANT-ASIAFOODS",
    "title": "Nguyên Tắc 5S & Quản Trị Trực Quan Trong Sản Xuất Thực Phẩm",
    "category": "SKILLS",
    "description": "Khóa học đào tạo thực hành chuyên sâu chuẩn hóa năng lực vận hành tại An Việt Manufacturing.",
    "durationHours": 4,
    "isRequired": false,
    "totalLessons": 6,
    "enrolledEmployees": 64,
    "passPercentage": 84,
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "minRequiredMinutes": 12,
    "actualWatchedMinutes": 14,
    "watchCount": 4,
    "isWatchRequirementMet": true
  },
  {
    "id": "CRS-04",
    "tenantId": "TENANT-ASIAFOODS",
    "title": "Tiêu Chuẩn Vệ Sinh An Toàn Thực Phẩm HACCP & ISO 22000",
    "category": "MANAGEMENT",
    "description": "Khóa học đào tạo thực hành chuyên sâu chuẩn hóa năng lực vận hành tại An Việt Manufacturing.",
    "durationHours": 5,
    "isRequired": true,
    "totalLessons": 7,
    "enrolledEmployees": 76,
    "passPercentage": 85,
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
    "minRequiredMinutes": 13,
    "actualWatchedMinutes": 16,
    "watchCount": 5,
    "isWatchRequirementMet": true
  },
  {
    "id": "CRS-05",
    "tenantId": "TENANT-ASIAFOODS",
    "title": "Kỹ Năng Đóng Gói Thành Phẩm & Kiểm Tra Mối Hàn Túi",
    "category": "SAFETY_LABOR",
    "description": "Khóa học đào tạo thực hành chuyên sâu chuẩn hóa năng lực vận hành tại An Việt Manufacturing.",
    "durationHours": 6,
    "isRequired": false,
    "totalLessons": 8,
    "enrolledEmployees": 88,
    "passPercentage": 86,
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    "minRequiredMinutes": 14,
    "actualWatchedMinutes": 18,
    "watchCount": 2,
    "isWatchRequirementMet": true
  },
  {
    "id": "CRS-06",
    "tenantId": "TENANT-ASIAFOODS",
    "title": "Quy Trình Kiểm Tra Chất Lượng Nguyên Vật Liệu Đầu Vào IQC",
    "category": "ONBOARDING",
    "description": "Khóa học đào tạo thực hành chuyên sâu chuẩn hóa năng lực vận hành tại An Việt Manufacturing.",
    "durationHours": 7,
    "isRequired": false,
    "totalLessons": 9,
    "enrolledEmployees": 100,
    "passPercentage": 87,
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    "minRequiredMinutes": 15,
    "actualWatchedMinutes": 10,
    "watchCount": 1,
    "isWatchRequirementMet": false
  },
  {
    "id": "CRS-07",
    "tenantId": "TENANT-ASIAFOODS",
    "title": "Bảo Dưỡng Phòng Ngừa (PM) & Khắc Phục Sự Cố Dây Chuyền Tự Động",
    "category": "SKILLS",
    "description": "Khóa học đào tạo thực hành chuyên sâu chuẩn hóa năng lực vận hành tại An Việt Manufacturing.",
    "durationHours": 2,
    "isRequired": true,
    "totalLessons": 10,
    "enrolledEmployees": 112,
    "passPercentage": 88,
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "minRequiredMinutes": 16,
    "actualWatchedMinutes": 22,
    "watchCount": 4,
    "isWatchRequirementMet": true
  },
  {
    "id": "CRS-08",
    "tenantId": "TENANT-ASIAFOODS",
    "title": "Kỹ Thuật Vận Hành Máy Dán Nhãn Decal Tự Động & Kiểm Soát Date",
    "category": "MANAGEMENT",
    "description": "Khóa học đào tạo thực hành chuyên sâu chuẩn hóa năng lực vận hành tại An Việt Manufacturing.",
    "durationHours": 3,
    "isRequired": false,
    "totalLessons": 11,
    "enrolledEmployees": 124,
    "passPercentage": 89,
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
    "minRequiredMinutes": 17,
    "actualWatchedMinutes": 24,
    "watchCount": 5,
    "isWatchRequirementMet": true
  },
  {
    "id": "CRS-09",
    "tenantId": "TENANT-ASIAFOODS",
    "title": "Kỹ Năng Lái Xe Nâng Hàng An Toàn Trong Nhà Kho Hẹp",
    "category": "SAFETY_LABOR",
    "description": "Khóa học đào tạo thực hành chuyên sâu chuẩn hóa năng lực vận hành tại An Việt Manufacturing.",
    "durationHours": 4,
    "isRequired": false,
    "totalLessons": 4,
    "enrolledEmployees": 136,
    "passPercentage": 90,
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    "minRequiredMinutes": 18,
    "actualWatchedMinutes": 26,
    "watchCount": 2,
    "isWatchRequirementMet": true
  },
  {
    "id": "CRS-10",
    "tenantId": "TENANT-ASIAFOODS",
    "title": "Quản Trị Kho Vận Theo Nguyên Tắc Nhập Trước Xuất Trước (FIFO)",
    "category": "ONBOARDING",
    "description": "Khóa học đào tạo thực hành chuyên sâu chuẩn hóa năng lực vận hành tại An Việt Manufacturing.",
    "durationHours": 5,
    "isRequired": true,
    "totalLessons": 5,
    "enrolledEmployees": 148,
    "passPercentage": 91,
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    "minRequiredMinutes": 19,
    "actualWatchedMinutes": 28,
    "watchCount": 3,
    "isWatchRequirementMet": true
  },
  {
    "id": "CRS-11",
    "tenantId": "TENANT-ASIAFOODS",
    "title": "Quy Trình Xử Lý Sự Cố Tràn Đổ Hóa Chất Vệ Sinh Công Nghiệp",
    "category": "SKILLS",
    "description": "Khóa học đào tạo thực hành chuyên sâu chuẩn hóa năng lực vận hành tại An Việt Manufacturing.",
    "durationHours": 6,
    "isRequired": false,
    "totalLessons": 6,
    "enrolledEmployees": 160,
    "passPercentage": 92,
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "minRequiredMinutes": 20,
    "actualWatchedMinutes": 14,
    "watchCount": 1,
    "isWatchRequirementMet": false
  },
  {
    "id": "CRS-12",
    "tenantId": "TENANT-ASIAFOODS",
    "title": "Kỹ Thuật Hàn TIG Inox & Gia Công Cơ Khí An Toàn",
    "category": "MANAGEMENT",
    "description": "Khóa học đào tạo thực hành chuyên sâu chuẩn hóa năng lực vận hành tại An Việt Manufacturing.",
    "durationHours": 7,
    "isRequired": false,
    "totalLessons": 7,
    "enrolledEmployees": 172,
    "passPercentage": 93,
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
    "minRequiredMinutes": 21,
    "actualWatchedMinutes": 22,
    "watchCount": 5,
    "isWatchRequirementMet": true
  },
  {
    "id": "CRS-13",
    "tenantId": "TENANT-ASIAFOODS",
    "title": "Kiểm Soát Vi Sinh Phòng Thí Nghiệm & Phương Pháp Đọc Khuẩn Lạc",
    "category": "SAFETY_LABOR",
    "description": "Khóa học đào tạo thực hành chuyên sâu chuẩn hóa năng lực vận hành tại An Việt Manufacturing.",
    "durationHours": 2,
    "isRequired": true,
    "totalLessons": 8,
    "enrolledEmployees": 184,
    "passPercentage": 94,
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    "minRequiredMinutes": 22,
    "actualWatchedMinutes": 24,
    "watchCount": 2,
    "isWatchRequirementMet": true
  },
  {
    "id": "CRS-14",
    "tenantId": "TENANT-ASIAFOODS",
    "title": "Quy Trình Giám Sát Điểm Kiểm Soát Tới Hạn CCP Trên Dây Chuyền",
    "category": "ONBOARDING",
    "description": "Khóa học đào tạo thực hành chuyên sâu chuẩn hóa năng lực vận hành tại An Việt Manufacturing.",
    "durationHours": 3,
    "isRequired": false,
    "totalLessons": 9,
    "enrolledEmployees": 196,
    "passPercentage": 95,
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    "minRequiredMinutes": 23,
    "actualWatchedMinutes": 26,
    "watchCount": 3,
    "isWatchRequirementMet": true
  },
  {
    "id": "CRS-15",
    "tenantId": "TENANT-ASIAFOODS",
    "title": "Phương Pháp Pha Chế & Phối Trộn Gia Vị Đúng Công Thức R&D",
    "category": "SKILLS",
    "description": "Khóa học đào tạo thực hành chuyên sâu chuẩn hóa năng lực vận hành tại An Việt Manufacturing.",
    "durationHours": 4,
    "isRequired": false,
    "totalLessons": 10,
    "enrolledEmployees": 208,
    "passPercentage": 96,
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "minRequiredMinutes": 24,
    "actualWatchedMinutes": 28,
    "watchCount": 4,
    "isWatchRequirementMet": true
  },
  {
    "id": "CRS-16",
    "tenantId": "TENANT-ASIAFOODS",
    "title": "Hướng Dẫn Khám Sức Khỏe Định Kỳ & Phòng Ngừa Bệnh Nghề Nghiệp",
    "category": "MANAGEMENT",
    "description": "Khóa học đào tạo thực hành chuyên sâu chuẩn hóa năng lực vận hành tại An Việt Manufacturing.",
    "durationHours": 5,
    "isRequired": true,
    "totalLessons": 11,
    "enrolledEmployees": 220,
    "passPercentage": 97,
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
    "minRequiredMinutes": 25,
    "actualWatchedMinutes": 17,
    "watchCount": 1,
    "isWatchRequirementMet": false
  },
  {
    "id": "CRS-17",
    "tenantId": "TENANT-ASIAFOODS",
    "title": "Quy Trình Khóa Biển Cảnh Báo An Toàn Nguồn Điện (LOTO)",
    "category": "SAFETY_LABOR",
    "description": "Khóa học đào tạo thực hành chuyên sâu chuẩn hóa năng lực vận hành tại An Việt Manufacturing.",
    "durationHours": 6,
    "isRequired": false,
    "totalLessons": 4,
    "enrolledEmployees": 232,
    "passPercentage": 82,
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    "minRequiredMinutes": 26,
    "actualWatchedMinutes": 32,
    "watchCount": 2,
    "isWatchRequirementMet": true
  },
  {
    "id": "CRS-18",
    "tenantId": "TENANT-ASIAFOODS",
    "title": "Kỹ Năng Làm Việc Nhóm & Giao Tiếp Trong Ca Sản Xuất",
    "category": "ONBOARDING",
    "description": "Khóa học đào tạo thực hành chuyên sâu chuẩn hóa năng lực vận hành tại An Việt Manufacturing.",
    "durationHours": 7,
    "isRequired": false,
    "totalLessons": 5,
    "enrolledEmployees": 244,
    "passPercentage": 83,
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    "minRequiredMinutes": 27,
    "actualWatchedMinutes": 34,
    "watchCount": 3,
    "isWatchRequirementMet": true
  },
  {
    "id": "CRS-19",
    "tenantId": "TENANT-ASIAFOODS",
    "title": "Đào Tạo Hội Nhập Văn Hóa Doanh Nghiệp An Việt Cho Nhân Viên Mới",
    "category": "SKILLS",
    "description": "Khóa học đào tạo thực hành chuyên sâu chuẩn hóa năng lực vận hành tại An Việt Manufacturing.",
    "durationHours": 2,
    "isRequired": true,
    "totalLessons": 6,
    "enrolledEmployees": 256,
    "passPercentage": 84,
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "minRequiredMinutes": 28,
    "actualWatchedMinutes": 36,
    "watchCount": 4,
    "isWatchRequirementMet": true
  },
  {
    "id": "CRS-20",
    "tenantId": "TENANT-ASIAFOODS",
    "title": "Quy Chế Tiền Lương, Chế Độ Phép Năm & BHXH Người Lao Động",
    "category": "MANAGEMENT",
    "description": "Khóa học đào tạo thực hành chuyên sâu chuẩn hóa năng lực vận hành tại An Việt Manufacturing.",
    "durationHours": 3,
    "isRequired": false,
    "totalLessons": 7,
    "enrolledEmployees": 268,
    "passPercentage": 85,
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
    "minRequiredMinutes": 29,
    "actualWatchedMinutes": 38,
    "watchCount": 5,
    "isWatchRequirementMet": true
  },
  {
    "id": "CRS-21",
    "tenantId": "TENANT-ASIAFOODS",
    "title": "Quy Trình Xử Lý Kỷ Luật Lao Động & Tuân Thủ Nội Quy Doanh Nghiệp",
    "category": "SAFETY_LABOR",
    "description": "Khóa học đào tạo thực hành chuyên sâu chuẩn hóa năng lực vận hành tại An Việt Manufacturing.",
    "durationHours": 4,
    "isRequired": false,
    "totalLessons": 8,
    "enrolledEmployees": 280,
    "passPercentage": 86,
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    "minRequiredMinutes": 30,
    "actualWatchedMinutes": 21,
    "watchCount": 1,
    "isWatchRequirementMet": false
  },
  {
    "id": "CRS-22",
    "tenantId": "TENANT-ASIAFOODS",
    "title": "Kỹ Năng Giám Sát Dây Chuyền Cho Trưởng Ca & Quản Đốc",
    "category": "ONBOARDING",
    "description": "Khóa học đào tạo thực hành chuyên sâu chuẩn hóa năng lực vận hành tại An Việt Manufacturing.",
    "durationHours": 5,
    "isRequired": true,
    "totalLessons": 9,
    "enrolledEmployees": 292,
    "passPercentage": 87,
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    "minRequiredMinutes": 31,
    "actualWatchedMinutes": 32,
    "watchCount": 3,
    "isWatchRequirementMet": true
  },
  {
    "id": "CRS-23",
    "tenantId": "TENANT-ASIAFOODS",
    "title": "Ứng Dụng Lean Six Sigma Loại Bỏ 8 Lãng Phí Trong Nhà Xưởng",
    "category": "SKILLS",
    "description": "Khóa học đào tạo thực hành chuyên sâu chuẩn hóa năng lực vận hành tại An Việt Manufacturing.",
    "durationHours": 6,
    "isRequired": false,
    "totalLessons": 10,
    "enrolledEmployees": 304,
    "passPercentage": 88,
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "minRequiredMinutes": 32,
    "actualWatchedMinutes": 34,
    "watchCount": 4,
    "isWatchRequirementMet": true
  },
  {
    "id": "CRS-24",
    "tenantId": "TENANT-ASIAFOODS",
    "title": "Kỹ Năng Đàm Phán Thương Mại Kênh Bán Buôn GT Cho Sales",
    "category": "MANAGEMENT",
    "description": "Khóa học đào tạo thực hành chuyên sâu chuẩn hóa năng lực vận hành tại An Việt Manufacturing.",
    "durationHours": 7,
    "isRequired": false,
    "totalLessons": 11,
    "enrolledEmployees": 316,
    "passPercentage": 89,
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
    "minRequiredMinutes": 33,
    "actualWatchedMinutes": 36,
    "watchCount": 5,
    "isWatchRequirementMet": true
  },
  {
    "id": "CRS-25",
    "tenantId": "TENANT-ASIAFOODS",
    "title": "Quản Lý Đơn Hàng & Chăm Sóc Khách Hàng Siêu Thị Kênh MT",
    "category": "SAFETY_LABOR",
    "description": "Khóa học đào tạo thực hành chuyên sâu chuẩn hóa năng lực vận hành tại An Việt Manufacturing.",
    "durationHours": 2,
    "isRequired": true,
    "totalLessons": 4,
    "enrolledEmployees": 328,
    "passPercentage": 90,
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    "minRequiredMinutes": 34,
    "actualWatchedMinutes": 38,
    "watchCount": 2,
    "isWatchRequirementMet": true
  },
  {
    "id": "CRS-26",
    "tenantId": "TENANT-ASIAFOODS",
    "title": "Kỹ Năng Đánh Giá Năng Lực & Phỏng Vấn Tuyển Dụng Nhân Sự",
    "category": "ONBOARDING",
    "description": "Khóa học đào tạo thực hành chuyên sâu chuẩn hóa năng lực vận hành tại An Việt Manufacturing.",
    "durationHours": 3,
    "isRequired": false,
    "totalLessons": 5,
    "enrolledEmployees": 40,
    "passPercentage": 91,
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    "minRequiredMinutes": 10,
    "actualWatchedMinutes": 7,
    "watchCount": 1,
    "isWatchRequirementMet": false
  },
  {
    "id": "CRS-27",
    "tenantId": "TENANT-ASIAFOODS",
    "title": "Bảo Mật Thông Tin Dữ Liệu Lương & Phòng Chống Mã Độc Tống Tiền",
    "category": "SKILLS",
    "description": "Khóa học đào tạo thực hành chuyên sâu chuẩn hóa năng lực vận hành tại An Việt Manufacturing.",
    "durationHours": 4,
    "isRequired": false,
    "totalLessons": 6,
    "enrolledEmployees": 52,
    "passPercentage": 92,
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "minRequiredMinutes": 11,
    "actualWatchedMinutes": 17,
    "watchCount": 4,
    "isWatchRequirementMet": true
  },
  {
    "id": "CRS-28",
    "tenantId": "TENANT-ASIAFOODS",
    "title": "Kỹ Thuật Nuôi Cấy & Định Danh Khuẩn Salmonella Trong Đồ Hộp",
    "category": "MANAGEMENT",
    "description": "Khóa học đào tạo thực hành chuyên sâu chuẩn hóa năng lực vận hành tại An Việt Manufacturing.",
    "durationHours": 5,
    "isRequired": true,
    "totalLessons": 7,
    "enrolledEmployees": 64,
    "passPercentage": 93,
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
    "minRequiredMinutes": 12,
    "actualWatchedMinutes": 19,
    "watchCount": 5,
    "isWatchRequirementMet": true
  },
  {
    "id": "CRS-29",
    "tenantId": "TENANT-ASIAFOODS",
    "title": "Vận Hành Hệ Thống Lọc Nước R.O & Khử Khoáng Nồi Hơi",
    "category": "SAFETY_LABOR",
    "description": "Khóa học đào tạo thực hành chuyên sâu chuẩn hóa năng lực vận hành tại An Việt Manufacturing.",
    "durationHours": 6,
    "isRequired": false,
    "totalLessons": 8,
    "enrolledEmployees": 76,
    "passPercentage": 94,
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    "minRequiredMinutes": 13,
    "actualWatchedMinutes": 21,
    "watchCount": 2,
    "isWatchRequirementMet": true
  },
  {
    "id": "CRS-30",
    "tenantId": "TENANT-ASIAFOODS",
    "title": "Kiểm Soát Chất Lượng Cảm Quan Mùi Vị & Màu Sắc Sản Phẩm",
    "category": "ONBOARDING",
    "description": "Khóa học đào tạo thực hành chuyên sâu chuẩn hóa năng lực vận hành tại An Việt Manufacturing.",
    "durationHours": 7,
    "isRequired": false,
    "totalLessons": 9,
    "enrolledEmployees": 88,
    "passPercentage": 95,
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    "minRequiredMinutes": 14,
    "actualWatchedMinutes": 23,
    "watchCount": 3,
    "isWatchRequirementMet": true
  },
  {
    "id": "CRS-31",
    "tenantId": "TENANT-ASIAFOODS",
    "title": "Quy Trình Thu Hồi Sản Phẩm Khẩn Cấp (Product Recall)",
    "category": "SKILLS",
    "description": "Khóa học đào tạo thực hành chuyên sâu chuẩn hóa năng lực vận hành tại An Việt Manufacturing.",
    "durationHours": 2,
    "isRequired": true,
    "totalLessons": 10,
    "enrolledEmployees": 100,
    "passPercentage": 96,
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "minRequiredMinutes": 15,
    "actualWatchedMinutes": 10,
    "watchCount": 1,
    "isWatchRequirementMet": false
  },
  {
    "id": "CRS-32",
    "tenantId": "TENANT-ASIAFOODS",
    "title": "An Toàn Làm Việc Trên Cao Khi Lắp Đặt Giá Kệ Kho Hàng",
    "category": "MANAGEMENT",
    "description": "Khóa học đào tạo thực hành chuyên sâu chuẩn hóa năng lực vận hành tại An Việt Manufacturing.",
    "durationHours": 3,
    "isRequired": false,
    "totalLessons": 11,
    "enrolledEmployees": 112,
    "passPercentage": 97,
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
    "minRequiredMinutes": 16,
    "actualWatchedMinutes": 17,
    "watchCount": 5,
    "isWatchRequirementMet": true
  },
  {
    "id": "CRS-33",
    "tenantId": "TENANT-ASIAFOODS",
    "title": "Kỹ Năng Lập Kế Hoạch Sản Xuất & Điều Độ Nguyên Liệu",
    "category": "SAFETY_LABOR",
    "description": "Khóa học đào tạo thực hành chuyên sâu chuẩn hóa năng lực vận hành tại An Việt Manufacturing.",
    "durationHours": 4,
    "isRequired": false,
    "totalLessons": 4,
    "enrolledEmployees": 124,
    "passPercentage": 82,
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    "minRequiredMinutes": 17,
    "actualWatchedMinutes": 19,
    "watchCount": 2,
    "isWatchRequirementMet": true
  },
  {
    "id": "CRS-34",
    "tenantId": "TENANT-ASIAFOODS",
    "title": "Quản Lý Chi Phí Nhân Công Trực Tiếp & Định Mức Tiêu Hao",
    "category": "ONBOARDING",
    "description": "Khóa học đào tạo thực hành chuyên sâu chuẩn hóa năng lực vận hành tại An Việt Manufacturing.",
    "durationHours": 5,
    "isRequired": true,
    "totalLessons": 5,
    "enrolledEmployees": 136,
    "passPercentage": 83,
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    "minRequiredMinutes": 18,
    "actualWatchedMinutes": 21,
    "watchCount": 3,
    "isWatchRequirementMet": true
  },
  {
    "id": "CRS-35",
    "tenantId": "TENANT-ASIAFOODS",
    "title": "Phương Pháp Đo Đạc Tiêu Hao Điện Năng Trong Phân Xưởng",
    "category": "SKILLS",
    "description": "Khóa học đào tạo thực hành chuyên sâu chuẩn hóa năng lực vận hành tại An Việt Manufacturing.",
    "durationHours": 6,
    "isRequired": false,
    "totalLessons": 6,
    "enrolledEmployees": 148,
    "passPercentage": 84,
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "minRequiredMinutes": 19,
    "actualWatchedMinutes": 23,
    "watchCount": 4,
    "isWatchRequirementMet": true
  },
  {
    "id": "CRS-36",
    "tenantId": "TENANT-ASIAFOODS",
    "title": "Kỹ Thuật Sấy Bơm Nhiệt & Giữ Trọn Dinh Dưỡng Nông Sản",
    "category": "MANAGEMENT",
    "description": "Khóa học đào tạo thực hành chuyên sâu chuẩn hóa năng lực vận hành tại An Việt Manufacturing.",
    "durationHours": 7,
    "isRequired": false,
    "totalLessons": 7,
    "enrolledEmployees": 160,
    "passPercentage": 85,
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
    "minRequiredMinutes": 20,
    "actualWatchedMinutes": 14,
    "watchCount": 1,
    "isWatchRequirementMet": false
  },
  {
    "id": "CRS-37",
    "tenantId": "TENANT-ASIAFOODS",
    "title": "Quy Chuẩn Đóng Gói Xuất Khẩu Thị Trường Châu Âu & Hoa Kỳ",
    "category": "SAFETY_LABOR",
    "description": "Khóa học đào tạo thực hành chuyên sâu chuẩn hóa năng lực vận hành tại An Việt Manufacturing.",
    "durationHours": 2,
    "isRequired": true,
    "totalLessons": 8,
    "enrolledEmployees": 172,
    "passPercentage": 86,
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    "minRequiredMinutes": 21,
    "actualWatchedMinutes": 27,
    "watchCount": 2,
    "isWatchRequirementMet": true
  },
  {
    "id": "CRS-38",
    "tenantId": "TENANT-ASIAFOODS",
    "title": "Kỹ Năng Sơ Cấp Cứu Hồi Sinh Tim Phổi (CPR) & Cầm Máu Tại Chỗ",
    "category": "ONBOARDING",
    "description": "Khóa học đào tạo thực hành chuyên sâu chuẩn hóa năng lực vận hành tại An Việt Manufacturing.",
    "durationHours": 3,
    "isRequired": false,
    "totalLessons": 9,
    "enrolledEmployees": 184,
    "passPercentage": 87,
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    "minRequiredMinutes": 22,
    "actualWatchedMinutes": 29,
    "watchCount": 3,
    "isWatchRequirementMet": true
  },
  {
    "id": "CRS-39",
    "tenantId": "TENANT-ASIAFOODS",
    "title": "Hướng Dẫn Sử Dụng Phần Mềm HRM Soft Dành Cho Quản Lý",
    "category": "SKILLS",
    "description": "Khóa học đào tạo thực hành chuyên sâu chuẩn hóa năng lực vận hành tại An Việt Manufacturing.",
    "durationHours": 4,
    "isRequired": false,
    "totalLessons": 10,
    "enrolledEmployees": 196,
    "passPercentage": 88,
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "minRequiredMinutes": 23,
    "actualWatchedMinutes": 31,
    "watchCount": 4,
    "isWatchRequirementMet": true
  },
  {
    "id": "CRS-40",
    "tenantId": "TENANT-ASIAFOODS",
    "title": "Quy Trình Tiếp Nhận & Giải Quyết Khiếu Nại Chất Lượng Khách Hàng",
    "category": "MANAGEMENT",
    "description": "Khóa học đào tạo thực hành chuyên sâu chuẩn hóa năng lực vận hành tại An Việt Manufacturing.",
    "durationHours": 5,
    "isRequired": true,
    "totalLessons": 11,
    "enrolledEmployees": 208,
    "passPercentage": 89,
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
    "minRequiredMinutes": 24,
    "actualWatchedMinutes": 33,
    "watchCount": 5,
    "isWatchRequirementMet": true
  },
  {
    "id": "CRS-41",
    "tenantId": "TENANT-ASIAFOODS",
    "title": "Kỹ Năng Quản Lý Căng Thẳng & Cân Bằng Công Việc Công Nhân Ca Đêm",
    "category": "SAFETY_LABOR",
    "description": "Khóa học đào tạo thực hành chuyên sâu chuẩn hóa năng lực vận hành tại An Việt Manufacturing.",
    "durationHours": 6,
    "isRequired": false,
    "totalLessons": 4,
    "enrolledEmployees": 220,
    "passPercentage": 90,
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    "minRequiredMinutes": 25,
    "actualWatchedMinutes": 17,
    "watchCount": 1,
    "isWatchRequirementMet": false
  },
  {
    "id": "CRS-42",
    "tenantId": "TENANT-ASIAFOODS",
    "title": "Quy Trình Bàn Giao Ca Trực & Ghi Chép Sổ Nhật Ký Kỹ Thuật",
    "category": "ONBOARDING",
    "description": "Khóa học đào tạo thực hành chuyên sâu chuẩn hóa năng lực vận hành tại An Việt Manufacturing.",
    "durationHours": 7,
    "isRequired": false,
    "totalLessons": 5,
    "enrolledEmployees": 232,
    "passPercentage": 91,
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    "minRequiredMinutes": 26,
    "actualWatchedMinutes": 27,
    "watchCount": 3,
    "isWatchRequirementMet": true
  },
  {
    "id": "CRS-43",
    "tenantId": "TENANT-ASIAFOODS",
    "title": "Phòng Ngừa Bụi Cháy Nổ Trong Silo Chứa Bột & Hạt Nông Sản",
    "category": "SKILLS",
    "description": "Khóa học đào tạo thực hành chuyên sâu chuẩn hóa năng lực vận hành tại An Việt Manufacturing.",
    "durationHours": 2,
    "isRequired": true,
    "totalLessons": 6,
    "enrolledEmployees": 244,
    "passPercentage": 92,
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "minRequiredMinutes": 27,
    "actualWatchedMinutes": 29,
    "watchCount": 4,
    "isWatchRequirementMet": true
  },
  {
    "id": "CRS-44",
    "tenantId": "TENANT-ASIAFOODS",
    "title": "Kỹ Thuật Cân Chỉnh Dao Cắt Màng Đóng Gói Siêu Tốc",
    "category": "MANAGEMENT",
    "description": "Khóa học đào tạo thực hành chuyên sâu chuẩn hóa năng lực vận hành tại An Việt Manufacturing.",
    "durationHours": 3,
    "isRequired": false,
    "totalLessons": 7,
    "enrolledEmployees": 256,
    "passPercentage": 93,
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
    "minRequiredMinutes": 28,
    "actualWatchedMinutes": 31,
    "watchCount": 5,
    "isWatchRequirementMet": true
  },
  {
    "id": "CRS-45",
    "tenantId": "TENANT-ASIAFOODS",
    "title": "Đạo Đức Nghề Nghiệp & Trách Nhiệm Xã Hội Doanh Nghiệp (CSR)",
    "category": "SAFETY_LABOR",
    "description": "Khóa học đào tạo thực hành chuyên sâu chuẩn hóa năng lực vận hành tại An Việt Manufacturing.",
    "durationHours": 4,
    "isRequired": false,
    "totalLessons": 8,
    "enrolledEmployees": 268,
    "passPercentage": 94,
    "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    "minRequiredMinutes": 29,
    "actualWatchedMinutes": 33,
    "watchCount": 2,
    "isWatchRequirementMet": true
  }
];

export const trainingCoursesLibrary = comprehensiveCourses;
