import { 
  TrainingGroupQuota, 
  EmployeeTrainingProgress, 
  ExternalTrainingCourse, 
  TrainingCommitment, 
  SkillMatrixItem, 
  InternalTrainer,
  TrainingBudgetReport 
} from '../types/hrm';

export const initialTrainingGroupQuotas: TrainingGroupQuota[] = [
  {
    id: 'QUOTA-01',
    groupId: 'MANAGEMENT',
    groupName: 'Khối Quản Lý / Lãnh Đạo',
    targetHoursPerYear: 40,
    minInternalRatio: 70,
    kpiWeightPercent: 10,
    description: 'Bao gồm Cán bộ quản lý từ cấp Phó Phòng, Trưởng Bộ phận, Quản đốc xưởng, Ban Giám đốc.',
    applicableRoles: 'Trưởng/Phó Phòng, Quản Đốc, Giám Đốc'
  },
  {
    id: 'QUOTA-02',
    groupId: 'SPECIALIST',
    groupName: 'Khối Chuyên Môn / Văn Phòng',
    targetHoursPerYear: 30,
    minInternalRatio: 70,
    kpiWeightPercent: 8,
    description: 'Bao gồm Kỹ sư công nghệ, Kế toán, Chuyên viên HR, QA/QC, Mua hàng, Kế hoạch, R&D.',
    applicableRoles: 'Kỹ sư, Chuyên viên, Kế toán, Giám sát'
  },
  {
    id: 'QUOTA-03',
    groupId: 'FACTORY',
    groupName: 'Khối Sản Xuất / Vận Hành Nhà Máy',
    targetHoursPerYear: 20,
    minInternalRatio: 75,
    kpiWeightPercent: 5,
    description: 'Bao gồm Công nhân trực tiếp chuyền sản xuất, Đóng gói, Vận hành máy móc, Kho vận, Bảo trì cơ điện.',
    applicableRoles: 'Công nhân, Vận hành máy, Tổ trưởng chuyền, Kỹ thuật bảo trì'
  },
  {
    id: 'QUOTA-04',
    groupId: 'ONBOARDING',
    groupName: 'Nhân Sự Mới (Hội Nhập / Thử Việc)',
    targetHoursPerYear: 16,
    minInternalRatio: 90,
    kpiWeightPercent: 15,
    description: 'Bắt buộc hoàn thành 100% trong 30 ngày đầu tiên (Văn hóa, Nội quy lao động, An toàn PCCC, Quy trình).',
    applicableRoles: 'Nhân viên mới tuyển dụng, Thử việc'
  }
];

export const initialEmployeeProgress: EmployeeTrainingProgress[] = [
  {
    id: 'PROG-01',
    employeeCode: 'AV-0102',
    employeeName: 'Nguyễn Văn A',
    department: 'Phòng Sản Xuất',
    roleTitle: 'Quản Đốc Phân Xưởng 1',
    groupId: 'MANAGEMENT',
    groupName: 'Khối Quản Lý',
    targetHours: 40,
    internalHours: 32,
    externalHours: 12,
    totalAccumulatedHours: 44,
    internalRatioActual: 72.7,
    completionRate: 110,
    kpiStatus: 'EXCELLENT',
    lastUpdated: '08/09/2026'
  },
  {
    id: 'PROG-02',
    employeeCode: 'AV-0145',
    employeeName: 'Trần Thị B',
    department: 'Phòng Kế Toán',
    roleTitle: 'Trưởng Phòng Kế Toán',
    groupId: 'MANAGEMENT',
    groupName: 'Khối Quản Lý',
    targetHours: 40,
    internalHours: 28,
    externalHours: 8,
    totalAccumulatedHours: 36,
    internalRatioActual: 77.8,
    completionRate: 90,
    kpiStatus: 'MET',
    lastUpdated: '05/09/2026'
  },
  {
    id: 'PROG-03',
    employeeCode: 'AV-0342',
    employeeName: 'Lê Hoàng C',
    department: 'Phòng Nhân Sự',
    roleTitle: 'Chuyên Viên L&D & Tiền Lương',
    groupId: 'SPECIALIST',
    groupName: 'Khối Chuyên Môn',
    targetHours: 30,
    internalHours: 24,
    externalHours: 6,
    totalAccumulatedHours: 30,
    internalRatioActual: 80.0,
    completionRate: 100,
    kpiStatus: 'MET',
    lastUpdated: '07/09/2026'
  },
  {
    id: 'PROG-04',
    employeeCode: 'AV-0219',
    employeeName: 'Phạm Văn D',
    department: 'Phòng Quản Lý Chất Lượng QA',
    roleTitle: 'Kỹ Sư Trưởng QA/QC',
    groupId: 'SPECIALIST',
    groupName: 'Khối Chuyên Môn',
    targetHours: 30,
    internalHours: 22,
    externalHours: 4,
    totalAccumulatedHours: 26,
    internalRatioActual: 84.6,
    completionRate: 86.7,
    kpiStatus: 'MET',
    lastUpdated: '02/09/2026'
  },
  {
    id: 'PROG-05',
    employeeCode: 'AV-0512',
    employeeName: 'Hoàng Thị E',
    department: 'Phòng Sản Xuất',
    roleTitle: 'Tổ Trưởng Chuyền Đóng Gói',
    groupId: 'FACTORY',
    groupName: 'Khối Sản Xuất',
    targetHours: 20,
    internalHours: 18,
    externalHours: 2,
    totalAccumulatedHours: 20,
    internalRatioActual: 90.0,
    completionRate: 100,
    kpiStatus: 'MET',
    lastUpdated: '04/09/2026'
  },
  {
    id: 'PROG-06',
    employeeCode: 'AV-0588',
    employeeName: 'Vũ Đình F',
    department: 'Phòng Sản Xuất',
    roleTitle: 'Vận Hành Máy Chiết Rót Tự Động',
    groupId: 'FACTORY',
    groupName: 'Khối Sản Xuất',
    targetHours: 20,
    internalHours: 14,
    externalHours: 0,
    totalAccumulatedHours: 14,
    internalRatioActual: 100.0,
    completionRate: 70,
    kpiStatus: 'WARNING_LOW_HOURS',
    lastUpdated: '01/09/2026'
  },
  {
    id: 'PROG-07',
    employeeCode: 'AV-0891',
    employeeName: 'Đặng Thu G',
    department: 'Phòng Nghiên Cứu & Phát Triển R&D',
    roleTitle: 'Chuyên Viên R&D (Mới Tuyển)',
    groupId: 'ONBOARDING',
    groupName: 'Nhân Sự Mới',
    targetHours: 16,
    internalHours: 16,
    externalHours: 0,
    totalAccumulatedHours: 16,
    internalRatioActual: 100.0,
    completionRate: 100,
    kpiStatus: 'MET',
    lastUpdated: '06/09/2026'
  },
  {
    id: 'PROG-08',
    employeeCode: 'AV-0417',
    employeeName: 'Bùi Minh H',
    department: 'Phòng Kỹ Thuật Cơ Điện',
    roleTitle: 'Kỹ Thuật Viên Bảo Trì Lò Hơi',
    groupId: 'FACTORY',
    groupName: 'Khối Sản Xuất',
    targetHours: 20,
    internalHours: 16,
    externalHours: 4,
    totalAccumulatedHours: 20,
    internalRatioActual: 80.0,
    completionRate: 100,
    kpiStatus: 'MET',
    lastUpdated: '03/09/2026'
  },
  {
    id: 'PROG-09',
    employeeCode: 'AV-0331',
    employeeName: 'Trịnh Quốc I',
    department: 'Phòng Mua Hàng & Cung Ứng',
    roleTitle: 'Chuyên Viên Mua Hàng Nguyên Liệu',
    groupId: 'SPECIALIST',
    groupName: 'Khối Chuyên Môn',
    targetHours: 30,
    internalHours: 20,
    externalHours: 4,
    totalAccumulatedHours: 24,
    internalRatioActual: 83.3,
    completionRate: 80,
    kpiStatus: 'MET',
    lastUpdated: '28/08/2026'
  },
  {
    id: 'PROG-10',
    employeeCode: 'AV-0663',
    employeeName: 'Phan Thị K',
    department: 'Phòng Sản Xuất',
    roleTitle: 'Công Nhân Đóng Gói Thùng',
    groupId: 'FACTORY',
    groupName: 'Khối Sản Xuất',
    targetHours: 20,
    internalHours: 10,
    externalHours: 0,
    totalAccumulatedHours: 10,
    internalRatioActual: 100.0,
    completionRate: 50,
    kpiStatus: 'WARNING_LOW_HOURS',
    lastUpdated: '20/08/2026'
  },
  {
    id: 'PROG-11',
    employeeCode: 'AV-0118',
    employeeName: 'Dương Văn L',
    department: 'Phòng Kỹ Thuật Cơ Điện',
    roleTitle: 'Trưởng Phòng Cơ Điện',
    groupId: 'MANAGEMENT',
    groupName: 'Khối Quản Lý',
    targetHours: 40,
    internalHours: 30,
    externalHours: 16,
    totalAccumulatedHours: 46,
    internalRatioActual: 65.2,
    completionRate: 115,
    kpiStatus: 'EXCELLENT',
    lastUpdated: '04/09/2026'
  },
  {
    id: 'PROG-12',
    employeeCode: 'AV-0359',
    employeeName: 'Đỗ Mai M',
    department: 'Phòng Kế Toán',
    roleTitle: 'Kế Toán Viên Chi Phí Giá Thành',
    groupId: 'SPECIALIST',
    groupName: 'Khối Chuyên Môn',
    targetHours: 30,
    internalHours: 18,
    externalHours: 4,
    totalAccumulatedHours: 22,
    internalRatioActual: 81.8,
    completionRate: 73.3,
    kpiStatus: 'WARNING_LOW_HOURS',
    lastUpdated: '25/08/2026'
  },
  {
    id: 'PROG-13',
    employeeCode: 'AV-0422',
    employeeName: 'Tạ Quang N',
    department: 'Phòng Kỹ Thuật Cơ Điện',
    roleTitle: 'Kỹ Sư Vận Hành Thiết Bị Áp Lực',
    groupId: 'FACTORY',
    groupName: 'Khối Sản Xuất',
    targetHours: 20,
    internalHours: 16,
    externalHours: 8,
    totalAccumulatedHours: 24,
    internalRatioActual: 66.7,
    completionRate: 120,
    kpiStatus: 'EXCELLENT',
    lastUpdated: '06/09/2026'
  },
  {
    id: 'PROG-14',
    employeeCode: 'AV-0902',
    employeeName: 'Hà Ngọc P',
    department: 'Phòng Kế Toán',
    roleTitle: 'Kế Toán Viên Nội Bộ (Mới Tuyển)',
    groupId: 'ONBOARDING',
    groupName: 'Nhân Sự Mới',
    targetHours: 16,
    internalHours: 12,
    externalHours: 0,
    totalAccumulatedHours: 12,
    internalRatioActual: 100.0,
    completionRate: 75,
    kpiStatus: 'WARNING_LOW_HOURS',
    lastUpdated: '02/09/2026'
  },
  {
    id: 'PROG-15',
    employeeCode: 'AV-0288',
    employeeName: 'Ngô Đình Q',
    department: 'Phòng Nghiên Cứu & Phát Triển R&D',
    roleTitle: 'Kỹ Sư Công Nghệ Thực Phẩm',
    groupId: 'SPECIALIST',
    groupName: 'Khối Chuyên Môn',
    targetHours: 30,
    internalHours: 25,
    externalHours: 8,
    totalAccumulatedHours: 33,
    internalRatioActual: 75.8,
    completionRate: 110,
    kpiStatus: 'EXCELLENT',
    lastUpdated: '05/09/2026'
  }
];

export const initialExternalCourses: ExternalTrainingCourse[] = [
  {
    id: 'EXT-01',
    courseName: 'Chứng Chỉ Kiểm Định Kỹ Thuật An Toàn Thiết Bị Áp Lực & Nồi Hơi',
    provider: 'Trung Tâm Kiểm Định Kỹ Thuật An Toàn Khu Vực 2 (Bộ LĐ-TB&XH)',
    category: 'COMPLIANCE',
    durationHours: 24,
    costPerPerson: 6500000,
    location: 'TP. Hồ Chí Minh (Học tập trung)',
    startDate: '15/03/2026',
    endDate: '18/03/2026',
    requiredCommitmentMonths: 12,
    enrolledCount: 3,
    status: 'COMPLETED'
  },
  {
    id: 'EXT-02',
    courseName: 'Huấn Luyện Người Làm Công Tác An Toàn Nhóm 2 (Nghị Định 44/2016)',
    provider: 'Viện An Toàn Vệ Sinh Lao Động Quốc Gia',
    category: 'COMPLIANCE',
    durationHours: 16,
    costPerPerson: 3200000,
    location: 'Bình Dương (Tại trung tâm đào tạo)',
    startDate: '10/05/2026',
    endDate: '12/05/2026',
    requiredCommitmentMonths: 6,
    enrolledCount: 4,
    status: 'COMPLETED'
  },
  {
    id: 'EXT-03',
    courseName: 'Đánh Giá Viên Trưởng Hệ Thống Quản Lý ATTP ISO 22000 & FSSC 22000',
    provider: 'Tổ Chức Chứng Nhận Quốc Tế SGS Vietnam',
    category: 'CERTIFICATION',
    durationHours: 40,
    costPerPerson: 14500000,
    location: 'TP. Hồ Chí Minh & Thực địa nhà máy',
    startDate: '08/07/2026',
    endDate: '13/07/2026',
    requiredCommitmentMonths: 24,
    enrolledCount: 2,
    status: 'COMPLETED'
  },
  {
    id: 'EXT-04',
    courseName: 'Nâng Cao Năng Lực Lãnh Đạo & Quản Trị Mục Tiêu OKR/KPI Cho Quản Lý Cấp Trung',
    provider: 'Trường Đào Tạo Doanh Nhân PACE',
    category: 'LEADERSHIP',
    durationHours: 20,
    costPerPerson: 9800000,
    location: 'TP. Hồ Chí Minh',
    startDate: '12/09/2026',
    endDate: '15/09/2026',
    requiredCommitmentMonths: 12,
    enrolledCount: 3,
    status: 'ENROLLING'
  },
  {
    id: 'EXT-05',
    courseName: 'Kỹ Thuật Phân Tích Dữ Liệu Sản Xuất & Tự Động Hóa SCADA/PLC Nâng Cao',
    provider: 'Viện Kỹ Thuật Công Nghệ VCCI & ĐH Bách Khoa',
    category: 'TECHNICAL',
    durationHours: 24,
    costPerPerson: 5500000,
    location: 'Bình Dương (Hybrid kết hợp xưởng)',
    startDate: '20/10/2026',
    endDate: '23/10/2026',
    requiredCommitmentMonths: 6,
    enrolledCount: 2,
    status: 'PLANNED'
  }
];

export const initialTrainingCommitments: TrainingCommitment[] = [
  {
    id: 'CMT-001',
    commitmentCode: 'CKĐT-2026/01',
    employeeId: 'AV-0422',
    employeeName: 'Tạ Quang N',
    department: 'Phòng Kỹ Thuật Cơ Điện',
    courseName: 'Chứng Chỉ Kiểm Định Kỹ Thuật An Toàn Thiết Bị Áp Lực & Nồi Hơi',
    provider: 'Trung Tâm Kiểm Định KTAT Khu Vực 2',
    trainingCost: 6500000,
    allowanceAmount: 1500000,
    totalInvestmentCost: 8000000,
    commitmentMonths: 12,
    startDate: '19/03/2026',
    endDate: '19/03/2027',
    servedMonths: 6,
    remainingMonths: 6,
    potentialRefundAmount: 4000000,
    status: 'ACTIVE',
    legalRef: 'Khoản 2 Điều 62 BLLĐ 2019 (Cam kết hoàn trả chi phí đào tạo tương ứng thời gian chưa phục vụ)'
  },
  {
    id: 'CMT-002',
    commitmentCode: 'CKĐT-2026/02',
    employeeId: 'AV-0219',
    employeeName: 'Phạm Văn D',
    department: 'Phòng Quản Lý Chất Lượng QA',
    courseName: 'Đánh Giá Viên Trưởng Hệ Thống Quản Lý ATTP ISO 22000 & FSSC 22000',
    provider: 'Tổ Chức SGS Vietnam',
    trainingCost: 14500000,
    allowanceAmount: 2500000,
    totalInvestmentCost: 17000000,
    commitmentMonths: 24,
    startDate: '15/07/2026',
    endDate: '15/07/2028',
    servedMonths: 2,
    remainingMonths: 22,
    potentialRefundAmount: 15583333,
    status: 'ACTIVE',
    legalRef: 'Khoản 2 Điều 62 BLLĐ 2019'
  },
  {
    id: 'CMT-003',
    commitmentCode: 'CKĐT-2026/03',
    employeeId: 'AV-0288',
    employeeName: 'Ngô Đình Q',
    department: 'Phòng Nghiên Cứu & Phát Triển R&D',
    courseName: 'Đánh Giá Viên Trưởng Hệ Thống Quản Lý ATTP ISO 22000 & FSSC 22000',
    provider: 'Tổ Chức SGS Vietnam',
    trainingCost: 14500000,
    allowanceAmount: 2500000,
    totalInvestmentCost: 17000000,
    commitmentMonths: 24,
    startDate: '15/07/2026',
    endDate: '15/07/2028',
    servedMonths: 2,
    remainingMonths: 22,
    potentialRefundAmount: 15583333,
    status: 'ACTIVE',
    legalRef: 'Khoản 2 Điều 62 BLLĐ 2019'
  },
  {
    id: 'CMT-004',
    commitmentCode: 'CKĐT-2025/11',
    employeeId: 'AV-0118',
    employeeName: 'Dương Văn L',
    department: 'Phòng Kỹ Thuật Cơ Điện',
    courseName: 'Chuyên Gia Tự Động Hóa Dây Chuyền Chế Biến Thực Phẩm',
    provider: 'Đại Học Bách Khoa TP.HCM',
    trainingCost: 12000000,
    allowanceAmount: 2000000,
    totalInvestmentCost: 14000000,
    commitmentMonths: 12,
    startDate: '15/08/2025',
    endDate: '15/08/2026',
    servedMonths: 12,
    remainingMonths: 0,
    potentialRefundAmount: 0,
    status: 'FULFILLED',
    legalRef: 'Khoản 2 Điều 62 BLLĐ 2019 (Đã hoàn thành xuất sắc 100% thời hạn cam kết)'
  }
];

export const initialSkillMatrix: SkillMatrixItem[] = [
  {
    id: 'SKILL-01',
    employeeId: 'AV-0102',
    employeeName: 'Nguyễn Văn A',
    department: 'Phòng Sản Xuất',
    roleTitle: 'Quản Đốc Phân Xưởng 1',
    skillName: 'Huấn Luyện & Kèm Cặp OJT (On-the-job Training)',
    category: 'LEADERSHIP',
    requiredLevel: 4,
    currentLevel: 4,
    gap: 0,
    recommendedCourseTitle: 'Đạt chuẩn Giảng viên nội bộ xuất sắc',
    status: 'QUALIFIED'
  },
  {
    id: 'SKILL-02',
    employeeId: 'AV-0588',
    employeeName: 'Vũ Đình F',
    department: 'Phòng Sản Xuất',
    roleTitle: 'Vận Hành Máy Chiết Rót Tự Động',
    skillName: 'Khắc Phục Sự Cố Kẹt Phôi & Hiệu Chỉnh Cảm Biến Quang',
    category: 'CORE_TECHNICAL',
    requiredLevel: 3,
    currentLevel: 2,
    gap: 1,
    recommendedCourseTitle: 'Kỹ Thuật Vận Hành & Khắc Phục Lỗi Máy Đóng Gói Chiết Rót',
    status: 'NEEDS_TRAINING'
  },
  {
    id: 'SKILL-03',
    employeeId: 'AV-0219',
    employeeName: 'Phạm Văn D',
    department: 'Phòng Quản Lý Chất Lượng QA',
    roleTitle: 'Kỹ Sư Trưởng QA/QC',
    skillName: 'Phân Tích Mối Nguy & Điểm Kiểm Soát Tới Hạn (HACCP/FSSC)',
    category: 'SAFETY_QUALITY',
    requiredLevel: 4,
    currentLevel: 4,
    gap: 0,
    recommendedCourseTitle: 'Đạt chuẩn Đánh giá viên Trưởng quốc tế',
    status: 'QUALIFIED'
  },
  {
    id: 'SKILL-04',
    employeeId: 'AV-0417',
    employeeName: 'Bùi Minh H',
    department: 'Phòng Kỹ Thuật Cơ Điện',
    roleTitle: 'Kỹ Thuật Viên Bảo Trì Lò Hơi',
    skillName: 'Vận Hành & Xả Cáu Cặn Nồi Hơi An Toàn PCCC',
    category: 'CORE_TECHNICAL',
    requiredLevel: 3,
    currentLevel: 3,
    gap: 0,
    recommendedCourseTitle: 'Đã hoàn thành kiểm định kỹ thuật KTAT',
    status: 'QUALIFIED'
  },
  {
    id: 'SKILL-05',
    employeeId: 'AV-0663',
    employeeName: 'Phan Thị K',
    department: 'Phòng Sản Xuất',
    roleTitle: 'Công Nhân Đóng Gói Thùng',
    skillName: 'Quy Tắc Vệ Sinh Cá Nhân & Kiểm Soát Dị Vật Sản Phẩm (GMP)',
    category: 'SAFETY_QUALITY',
    requiredLevel: 2,
    currentLevel: 1,
    gap: 1,
    recommendedCourseTitle: 'Tiêu Chuẩn Vệ Sinh An Toàn Thực Phẩm HACCP & ISO 22000',
    status: 'NEEDS_TRAINING'
  },
  {
    id: 'SKILL-06',
    employeeId: 'AV-0359',
    employeeName: 'Đỗ Mai M',
    department: 'Phòng Kế Toán',
    roleTitle: 'Kế Toán Viên Chi Phí',
    skillName: 'Khai Thác Báo Cáo Phân Tích Chi Phí Giá Thành Trên ERP',
    category: 'DIGITAL',
    requiredLevel: 3,
    currentLevel: 2,
    gap: 1,
    recommendedCourseTitle: 'Phân Tích Dữ Liệu Giá Thành & Định Mức Hao Hụt Nguyên Vật Liệu',
    status: 'TRAINING_IN_PROGRESS'
  },
  {
    id: 'SKILL-07',
    employeeId: 'AV-0422',
    employeeName: 'Tạ Quang N',
    department: 'Phòng Kỹ Thuật Cơ Điện',
    roleTitle: 'Kỹ Sư Vận Hành Thiết Bị Áp Lực',
    skillName: 'Quy Trình Kiểm Tra Van An Toàn & Thử Thủy Lực Bình Khí Nén',
    category: 'SAFETY_QUALITY',
    requiredLevel: 4,
    currentLevel: 4,
    gap: 0,
    recommendedCourseTitle: 'Đạt cấp độ Giảng viên chuyên gia nội bộ',
    status: 'QUALIFIED'
  },
  {
    id: 'SKILL-08',
    employeeId: 'AV-0891',
    employeeName: 'Đặng Thu G',
    department: 'Phòng Nghiên Cứu & Phát Triển R&D',
    roleTitle: 'Chuyên Viên R&D (Mới Tuyển)',
    skillName: 'Quy Chuẩn Thử Nghiệm Cảm Quan & Đo Độ Ẩm Mẫu Thực Phẩm',
    category: 'CORE_TECHNICAL',
    requiredLevel: 2,
    currentLevel: 2,
    gap: 0,
    recommendedCourseTitle: 'Đã hoàn thành giai đoạn thử việc OJT',
    status: 'QUALIFIED'
  }
];

export const initialInternalTrainers: InternalTrainer[] = [
  {
    id: 'TRN-01',
    trainerCode: 'GVNB-01',
    employeeId: 'AV-0102',
    employeeName: 'Nguyễn Văn A',
    department: 'Phòng Sản Xuất',
    roleTitle: 'Quản Đốc Phân Xưởng 1',
    specialtyTopics: ['5S & Kaizen Hiện Trường', 'Kỹ Năng Giám Sát Chuyền', 'An Toàn Vận Hành Nhà Máy'],
    totalTeachingHours: 28,
    hourlyAllowanceRate: 250000,
    totalAllowancePaid: 7000000,
    studentRatingAverage: 4.9,
    totalClassesTaught: 7,
    status: 'ACTIVE'
  },
  {
    id: 'TRN-02',
    trainerCode: 'GVNB-02',
    employeeId: 'AV-0145',
    employeeName: 'Trần Thị B',
    department: 'Phòng Kế Toán',
    roleTitle: 'Trưởng Phòng Kế Toán',
    specialtyTopics: ['Quy Trình Tạm Ứng & Thanh Toán', 'Kiểm Soát Chi Phí Bộ Phận', 'Hóa Đơn Điện Tử'],
    totalTeachingHours: 16,
    hourlyAllowanceRate: 250000,
    totalAllowancePaid: 4000000,
    studentRatingAverage: 4.82,
    totalClassesTaught: 4,
    status: 'ACTIVE'
  },
  {
    id: 'TRN-03',
    trainerCode: 'GVNB-03',
    employeeId: 'AV-0342',
    employeeName: 'Lê Hoàng C',
    department: 'Phòng Nhân Sự',
    roleTitle: 'Chuyên Viên L&D & Tiền Lương',
    specialtyTopics: ['Hội Nhập Văn Hóa Doanh Nghiệp', 'Nội Quy Lao Động & BLLĐ 2019', 'Quy Trình Nghỉ Phép & Đơn Từ'],
    totalTeachingHours: 32,
    hourlyAllowanceRate: 200000,
    totalAllowancePaid: 6400000,
    studentRatingAverage: 4.88,
    totalClassesTaught: 8,
    status: 'ACTIVE'
  },
  {
    id: 'TRN-04',
    trainerCode: 'GVNB-04',
    employeeId: 'AV-0219',
    employeeName: 'Phạm Văn D',
    department: 'Phòng Quản Lý Chất Lượng QA',
    roleTitle: 'Kỹ Sư Trưởng QA/QC',
    specialtyTopics: ['Thực Hành Tốt Vệ Sinh (GMP)', 'Kiểm Soát Mối Nguy HACCP', 'Quy Chuẩn Vệ Sinh Máy Móc'],
    totalTeachingHours: 24,
    hourlyAllowanceRate: 250000,
    totalAllowancePaid: 6000000,
    studentRatingAverage: 4.94,
    totalClassesTaught: 6,
    status: 'ACTIVE'
  },
  {
    id: 'TRN-05',
    trainerCode: 'GVNB-05',
    employeeId: 'AV-0118',
    employeeName: 'Dương Văn L',
    department: 'Phòng Kỹ Thuật Cơ Điện',
    roleTitle: 'Trưởng Phòng Cơ Điện',
    specialtyTopics: ['An Toàn Điện Hạ Thế & Trung Thế', 'Quy Tắc Ứng Phó Khẩn Cấp PCCC', 'Vận Hành Hệ Thống Lạnh Công Nghiệp'],
    totalTeachingHours: 20,
    hourlyAllowanceRate: 250000,
    totalAllowancePaid: 5000000,
    studentRatingAverage: 4.85,
    totalClassesTaught: 5,
    status: 'ACTIVE'
  }
];

export const initialBudgetReport: TrainingBudgetReport = {
  year: 2026,
  totalApprovedBudget: 450000000,
  totalSpentBudget: 285400000,
  internalTrainingSpent: 84400000,
  externalTrainingSpent: 201000000,
  avgCostPerEmployee: 1902666,
  internalHoursPercentage: 77.2,
  totalEmployeesTargetMet: 12,
  totalEmployeesUnderTarget: 3
};

export const calculateTrainingBondRefund = (
  totalInvestment: number, 
  commitmentMonths: number, 
  servedMonths: number
): { remainingMonths: number; refundAmount: number; refundPercentage: number } => {
  if (commitmentMonths <= 0) return { remainingMonths: 0, refundAmount: 0, refundPercentage: 0 };
  const safeServed = Math.min(commitmentMonths, Math.max(0, servedMonths));
  const remainingMonths = commitmentMonths - safeServed;
  const refundAmount = Math.round(totalInvestment * (remainingMonths / commitmentMonths));
  const refundPercentage = Math.round((remainingMonths / commitmentMonths) * 100);
  return { remainingMonths, refundAmount, refundPercentage };
};
